'use client';

import { useMemo } from 'react';
import MapComponent, { MapProps } from './MapComponent';
import { Trip, TripEvent, BucketListItem } from '@pplaner/shared';
import { AIRPORTS } from '@pplaner/shared';
import { CATEGORY_MAP } from '@pplaner/shared';

interface TripMapProps {
    trip: Trip;
    viewMode?: 'dashboard' | 'itinerary' | 'bucketlist' | 'basic';
    markers?: MapProps['markers']; // Optional override/custom markers
    highlightedId?: string;
    activeDay?: number; // 1-based index to highlight only a specific day's path/markers
    onMarkerClick?: (id: string) => void;
    
    // Planning / Itinerary specific
    mapSegments?: MapProps['mapSegments'];
    isMapPlanningMode?: boolean;
    mapInsertAfterIndex?: number | null;
    onPolylineClick?: (insertAfterIndex: number) => void;
    onLoad?: (map: google.maps.Map) => void;
    
    showFlights?: boolean;
    showPath?: boolean;
    showRegions?: boolean;
    showBucketList?: boolean;
    className?: string;
}

export default function TripMap({
    trip,
    viewMode = 'dashboard',
    markers: customMarkers,
    highlightedId,
    activeDay,
    onMarkerClick,
    mapSegments,
    isMapPlanningMode,
    mapInsertAfterIndex,
    onPolylineClick,
    onLoad,
    showFlights = true,
    showPath = true,
    showRegions = true,
    showBucketList = true,
    className
}: TripMapProps) {
    
    // 1. Gather Markers
    const defaultMarkers = useMemo(() => {
        if (!trip) return [];
        const m: NonNullable<MapProps['markers']> = [];

        // --- Flights (Airports) ---
        if (showFlights) {
            trip.flights?.forEach((f, idx) => {
                [
                    { code: f.departureLocation, lat: f.departureLat, lng: f.departureLng, label: '출발', id: `air-dep-${f.id || idx}` },
                    { code: f.arrivalLocation, lat: f.arrivalLat, lng: f.arrivalLng, label: '도착', id: `air-arr-${f.id || idx}` }
                ].forEach(loc => {
                    const airport = AIRPORTS.find(a => a.code === loc.code);
                    const lat = loc.lat || airport?.lat;
                    const lng = loc.lng || airport?.lng;
                    if (lat && lng) {
                        m.push({
                            id: loc.id,
                            lat,
                            lng,
                            title: airport ? `${airport.nameKo} (${airport.code})` : loc.code || '공항',
                            type: 'airport',
                            category: 'transport'
                        });
                    }
                });
            });
        }

        // --- Accommodation ---
        trip.accommodation?.forEach((acc, idx) => {
            if (acc.lat && acc.lng) {
                m.push({
                    id: acc.id || `acc-${idx}`,
                    lat: acc.lat,
                    lng: acc.lng,
                    title: acc.name,
                    type: 'accommodation',
                    category: 'accommodation',
                    description: acc.location
                });
            }
        });

        // --- Daily Events (Itinerary) ---
        trip.dailyTimeline?.forEach((day, dayIdx) => {
            const isDayMatch = activeDay === undefined || activeDay === (dayIdx + 1);
            if (!isDayMatch && viewMode === 'itinerary') return;

            day.events.forEach((event) => {
                if (event.location?.lat && event.location?.lng) {
                    // Skip duplicates if already added (e.g. from accommodation/airport auto-events)
                    if (event.autoGeneratedType === 'stay' || event.autoGeneratedType === 'flight') return;
                    
                    m.push({
                        id: event.id,
                        lat: event.location.lat,
                        lng: event.location.lng,
                        title: event.title,
                        type: event.type === 'meal' ? 'restaurant' : 'attraction',
                        category: event.type,
                        day: dayIdx + 1,
                        highlighted: highlightedId === event.id
                    });
                }
            });
        });

        // --- Bucket List ---
        if (showBucketList || viewMode === 'bucketlist') {
            trip.bucketList?.forEach((item) => {
                if (item.place?.lat && item.place?.lng) {
                    // Avoid double markers if already in itinerary
                    if (m.some(existing => existing.id === item.id)) return;

                    m.push({
                        id: item.id,
                        lat: item.place.lat,
                        lng: item.place.lng,
                        title: item.title,
                        type: 'interest',
                        category: (item.mainCategory as any) || 'interest',
                        isWishlist: true,
                        description: item.place.address
                    });
                }
            });
        }

        // --- Transport Points (Rental/Public) ---
        trip.driving?.forEach(d => {
            if (d.pickupLat && d.pickupLng) m.push({ lat: d.pickupLat, lng: d.pickupLng, title: `픽업: ${d.pickupLocation}`, type: 'transport', id: `rental-p-${d.id}` });
            if (d.returnLat && d.returnLng) m.push({ lat: d.returnLat, lng: d.returnLng, title: `반납: ${d.returnLocation}`, type: 'transport', id: `rental-r-${d.id}` });
        });
        trip.publicTransport?.forEach(p => {
            if (p.departureLat && p.departureLng) m.push({ lat: p.departureLat, lng: p.departureLng, title: `출발: ${p.departureLocation}`, type: 'transport', id: `pub-dep-${p.id}` });
            if (p.arrivalLat && p.arrivalLng) m.push({ lat: p.arrivalLat, lng: p.arrivalLng, title: `도착: ${p.arrivalLocation}`, type: 'transport', id: `pub-arr-${p.id}` });
        });

        // Unique filter to prevent marker overlap same-ID items
        return m.filter((item, index, self) =>
            index === self.findIndex((t) => t.id === item.id)
        );
    }, [trip, viewMode, highlightedId, activeDay, showFlights, showBucketList]);

    const finalMarkers = useMemo(() => {
        if (!customMarkers) return defaultMarkers;
        // Merge strategy: customMarkers take priority on overlap
        const combined = [...customMarkers];
        defaultMarkers.forEach(dm => {
            if (!combined.some(cm => cm.id === dm.id)) {
                combined.push(dm);
            }
        });
        return combined;
    }, [customMarkers, defaultMarkers]);

    // 2. Flight Paths
    const flightPaths = useMemo(() => {
        if (!showFlights || !trip?.flights) return [];
        return trip.flights.map(f => {
            const depAir = AIRPORTS.find(a => a.code === f.departureLocation);
            const arrAir = AIRPORTS.find(a => a.code === f.arrivalLocation);
            const from = { lat: f.departureLat || depAir?.lat, lng: f.departureLng || depAir?.lng };
            const to = { lat: f.arrivalLat || arrAir?.lat, lng: f.arrivalLng || arrAir?.lng };
            if (from.lat && from.lng && to.lat && to.lng) {
                return { from: from as {lat: number, lng: number}, to: to as {lat: number, lng: number} };
            }
            return null;
        }).filter(Boolean) as NonNullable<MapProps['flightPaths']>;
    }, [trip, showFlights]);

    // 3. Itinerary Paths
    const fullPath = useMemo(() => {
        if (!showPath || !trip?.dailyTimeline) return [];
        const path: { lat: number; lng: number }[] = [];
        
        trip.dailyTimeline.forEach((day, dayIdx) => {
            if (activeDay !== undefined && activeDay !== (dayIdx + 1)) return;

            day.events?.forEach(event => {
                if (event.location?.lat && event.location?.lng) {
                    path.push({ lat: event.location.lat, lng: event.location.lng });
                }
            });
        });
        return path;
    }, [trip, showPath, activeDay]);

    const initialCenter = useMemo(() => {
        if (trip.locations?.center) return trip.locations.center;
        if (fullPath.length > 0) return fullPath[0];
        if (finalMarkers.length > 0) return { lat: finalMarkers[0].lat, lng: finalMarkers[0].lng };
        return { lat: 37.5665, lng: 126.9780 }; // Seoul fallback
    }, [trip, finalMarkers, fullPath]);

    return (
        <MapComponent
            center={initialCenter}
            zoom={viewMode === 'dashboard' ? 10 : 12}
            markers={finalMarkers}
            flightPaths={flightPaths}
            path={fullPath}
            regions={showRegions ? trip.locations?.regions : []}
            highlightedId={highlightedId}
            onMarkerClick={onMarkerClick}
            mapSegments={mapSegments}
            isMapPlanningMode={isMapPlanningMode}
            mapInsertAfterIndex={mapInsertAfterIndex}
            onPolylineClick={onPolylineClick}
            onLoad={onLoad}
        />
    );
}
