export const COMPANY_EN_NAMES: Record<string, string> = {
    "IRいしかわ鉄道": "IR Ishikawa Railway",
    "あいの風とやま鉄道": "Ainokaze Toyama Railway",
    "いすみ鉄道": "Isumi Railway",
    "えちごトキめき鉄道": "Echigo Tokimeki Railway",
    "えちぜん鉄道": "Echizen Railway",
    "ゆりかもめ": "Yurikamome",
    "わたらせ渓谷鐵道": "Watarase Keikoku Railway",
    "一畑電車": "Ichibata Electric Railway",
    "万葉線": "Manyo Line",
    "三岐鉄道": "Sangi Railway",
    "三陸鉄道": "Sanriku Railway",
    "上信電鉄": "Jōshin Dentetsu",
    "上毛電気鉄道": "Jōmō Electric Railway",
    "上田電鉄": "Ueda Electric Railway",
    "井原鉄道": "Ibara Railway",
    "伊予鉄道": "Iyo Railway",
    "伊勢鉄道": "Ise Railway",
    "伊豆急行": "Izukyū Corporation",
    "伊豆箱根鉄道": "Izuhakone Railway",
    "伊賀鉄道": "Iga Railway",
    "会津鉄道": "Aizu Railway",
    "東日本旅客鉄道": "JR East",
    "西日本旅客鉄道": "JR West",
    "東海旅客鉄道": "JR Central",
    "北海道旅客鉄道": "JR Hokkaido",
    "九州旅客鉄道": "JR Kyushu",
    "四国旅客鉄道": "JR Shikoku",
    "日本貨物鉄道": "JR Freight",
    "東京地下鉄": "Tokyo Metro",
    "東京都交通局": "Toei Subway",
    "京王電鉄": "Keio Corporation",
    "京成電鉄": "Keisei Electric Railway",
    "京浜急行電鉄": "Keikyu Corporation",
    "東急電鉄": "Tokyu Railways",
    "東武鉄道": "Tobu Railway",
    "西武鉄道": "Seibu Railway",
    "小田急電鉄": "Odakyu Electric Railway",
    "相模鉄道": "Sagami Railway",
    "名古屋鉄道": "Nagoya Railroad",
    "近畿日本鉄道": "Kintetsu Railway",
    "南海電気鉄道": "Nankai Electric Railway",
    "京阪電気鉄道": "Keihan Electric Railway",
    "阪急電鉄": "Hankyu Corporation",
    "阪神電気鉄道": "Hanshin Electric Railway",
    "西日本鉄道": "Nishitetsu Railway",
    "相鉄": "Sotetsu",
    "名鉄": "Meitetsu",
    "近鉄": "Kintetsu",
    "阪急": "Hankyu",
    "阪神": "Hanshin",
    "京急": "Keikyu",
    "京成": "Keisei",
    "京王": "Keio",
    "東急": "Tokyu",
    "東武": "Tobu",
    "西武": "Seibu",
    "小田急": "Odakyu",
    "四日市あすなろう鉄道": "Yokkaichi Asonarou Railway",
    "弘南鉄道": "Kōnan Railway",
    "秋田内陸縦貫鉄道": "Akita Nairiku Jūkan Railway",
    "仙台空港鉄道": "Sendai Airport Transit",
    "新京成電鉄": "Shin-Keisei Railway",
    "真岡鐵道": "Mooka Railway",
    "東葉高速鉄道": "Tōyō Rapid Railway",
    "箱根登山鉄道": "Hakone Tozan Railway",
    "北総鉄道": "Hokusō Railway",
    "北陸鉄道": "Hokuriku Railroad",
    "福井鉄道": "Fukui Railway",
    "静岡鉄道": "Shizuoka Railway",
    "天竜浜名湖鉄道": "Tenryū Hamanako Railroad",
    "遠州鉄道": "Enshū Railway",
    "大井川鐵道": "Ōigawa Railway",
    "豊橋鉄道": "Toyohashi Railroad",
    "明知鉄道": "Akechi Railway",
    "樽見鉄道": "Tarumi Railway",
    "養老鉄道": "Yōrō Railway",
    "近江鉄道": "Ohmi Railway",
    "嵯峨野観光鉄道": "Sagano Scenic Railway",
    "水間鉄道": "Mizuma Railway",
    "北条鉄道": "Hōjō Railway",
    "若桜鉄道": "Wakasa Railway",
    "土佐くろしお鉄道": "Tosa Kuroshio Railway",
    "甘木鉄道": "Amagi Railway",
    "南阿蘇鉄道": "Minamiaso Railway",
    "道南いさりび鉄道": "South Hokkaido Railway Company",
    "青い森鉄道": "Aoimori Railway",
    "津軽鉄道": "Tsugaru Railway",
    "由利高原鉄道": "Yuri Kōgen Railway",
    "山形鉄道": "Yamagata Railway",
    "阿武隈急行": "AbukumaExpress",
    "福島交通": "Fukushima Transportation",
    "ひたちなか海浜鉄道": "Hitachinaka Seaside Railway",
    "関東鉄道": "Kantō Railway",
    "鹿島臨海鉄道": "Kashima Rinkai Railway",
    "野岩鉄道": "Yagan Railway",
    "秩父鉄道": "Chichibu Railway",
    "埼玉高速鉄道": "Saitama Railway",
    "銚子電気鉄道": "Chōshi Electric Railway",
    "小湊鉄道": "Kominato Railway",
    "流鉄": "Ryūtetsu",
    "芝山鉄道": "Shibayama Railway",
    "首都圏新都市鉄道": "Metropolitan Intercity Railway Company (Tsukuba Express)",
    "東京臨海高速鉄道": "Tōkyō Waterfront Area Rapid Transit (Rinkai Line)",
    "横浜高速鉄道": "Yokohama Minatomirai Railway",
    "北越急行": "Hokuetsu Express",
    "黒部峡谷鉄道": "Kurobe Gorge Railway",
    "富山地方鉄道": "Toyama Chihō Railway",
    "のと鉄道": "Noto Railway",
    "ハピラインふくい": "Hapi-Line Fukui",
    "富士急行": "Fuji Kyūkō",
    "アルピコ交通": "Alpico Kōtsū",
    "長野電気鉄道": "Nagano Electric Railway",
    "しなの鉄道": "Shinano Railway",
    "長良川鉄道": "Nagaragawa Railway",
    "岳南電車": "Gakunan Railway",
    "愛知環状鉄道": "Aichi Loop Line Company",
    "東海交通事業": "Tōkai Transport Service",
    "信楽高原鐵道": "Shigaraki Kohgen Railway",
    "叡山電鉄": "Eizan Electric Railway",
    "神戸電気鉄道": "Kobe Electric Railway",
    "能勢電気鉄道": "Nose Electric Railway",
    "紀州鉄道": "Kishū Railway",
    "和歌山電鐵": "Wakayama Electric Railway",
    "智頭急行": "Chizu Express",
    "水島臨海鉄道": "Mizushima Rinkai Railway",
    "錦川鉄道": "Nishikigawa Railway",
    "阿佐海岸鉄道": "Asa Kaigan Railway",
    "高松琴平電気鉄道": "Takamatsu-Kotohira Electric Railroad",
    "平成筑豊鉄道": "Heisei Chikuhō Railway",
    "松浦鉄道": "Matsuura Railway",
    "島原鉄道": "Shimabara Railway",
    "肥薩おれんじ鉄道": "Hisatsu Orange Railway",
    "くま川鉄道": "Kumagawa Railroad",
    "熊本電気鉄道": "Kumamoto Electric Railway",
    "千葉都市モノレール": "Chiba Urban Monorail",
    "東京モノレール": "Tokyo Monorail",
    "多摩都市モノレール": "Tama Toshi Monorail",
    "湘南モノレール": "Shōnan Monorail",
    "大阪モノレール": "Ōsaka Monorail",
    "沖縄都市モノレール": "Okinawa Urban Monorail (Yui Rail)",
    "愛知高速交通": "Aichi Rapid Transit (Linimo)",
    "広島高速交通": "Hiroshima Rapid Transit (Astram Line)",
    "名古屋ガイドウェイバス": "Nagoya Guideway Bus (Yutorīto Line)",
    "埼玉新都市交通": "Saitama New Urban Transit (New Shuttle)",
    "江ノ島電鉄": "Enoshima Electric Railway",
    "阪堺電気軌道": "Hankai Electric Tramway",
    "広島電鉄": "Hiroshima Electric Railway",
    "長崎電気軌道": "Nagasaki Electric Tramway",
    "岡山電気軌道": "Okayama Electric Tramway",
    "宇都宮ライトレール": "Utsunomiya Light Rail"
};

export const LINE_EN_NAMES: Record<string, string> = {
    "東海道新幹線": "Tokaido Shinkansen",
    "山陽新幹線": "San'yo Shinkansen",
    "東北新幹線": "Tohoku Shinkansen",
    "上越新幹線": "Joetsu Shinkansen",
    "山形新幹線": "Yamagata Shinkansen",
    "秋田新幹線": "Akita Shinkansen",
    "北陸新幹線": "Hokuriku Shinkansen",
    "九州新幹線": "Kyushu Shinkansen",
    "北海道新幹線": "Hokkaido Shinkansen",
    "根室本線": "Nemuro Main Line",
    "千歳線": "Chitose Line",
    "石勝線": "Sekisho Line",
    "日高本線": "Hidaka Main Line",
    "札沼線": "Sassho Line",
    "留萌本線": "Rumoi Main Line",
    "富良野線": "Furano Line",
    "宗谷本線": "Soya Main Line",
    "石北本線": "Sekihoku Main Line",
    "釧網本線": "Senmo Main Line",
    "海峡線": "Kaikyo Line",
    "大湊線": "Ominato Line",
    "五能線": "Gono Line",
    "津軽線": "Tsugaru Line",
    "八戸線": "Hachinohe Line",
    "大船渡線": "Ofunato Line",
    "釜石線": "Kamaishi Line",
    "北上線": "Kitakami Line",
    "田沢湖線": "Tazawako Line",
    "花輪線": "Hanawa Line",
    "山田線": "Yamada Line (JR East)",
    "羽越本線": "Uetsu Main Line",
    "男鹿線": "Oga Line",
    "仙山線": "Senzan Line",
    "左沢線": "Aterazawa Line",
    "米坂線": "Yonesaka Line",
    "陸羽西線": "Rikuu West Line",
    "陸羽東線": "Rikuu East Line",
    "仙石線": "Senseki Line",
    "石巻線": "Ishinomaki Line",
    "気仙沼線": "Kesennuma Line",
    "磐越西線": "Ban'etsu West Line",
    "只見線": "Tadami Line",
    "磐越東線": "Ban'etsu East Line",
    "山手線": "Yamanote Line",
    "南武線": "Nambu Line",
    "鶴見線": "Tsurumi Line",
    "武蔵野線": "Musashino Line",
    "横浜線": "Yokohama Line",
    "根岸線": "Negishi Line",
    "横須賀線": "Yokosuka Line",
    "相模線": "Sagami Line",
    "総武本線": "Sobu Main Line",
    "青梅線": "Ome Line",
    "五日市線": "Itsukaichi Line",
    "宇都宮線": "Utsunomiya Line",
    "埼京線": "Saikyo Line",
    "川越線": "Kawagoe Line",
    "高崎線": "Takasaki Line",
    "外房線": "Sotobo Line",
    "内房線": "Uchibo Line",
    "京葉線": "Keiyo Line",
    "成田線": "Narita Line",
    "鹿島線": "Kashima Line",
    "久留里線": "Kururi Line",
    "東金線": "Togane Line",
    "京浜東北線": "Keihin-Tohoku Line",
    "湘南新宿ライン": "Shonan–Shinjuku Line",
    "上野東京ライン": "Ueno–Tokyo Line",
    "烏山線": "Karasuyama Line",
    "吾妻線": "Agatsuma Line",
    "信越本線": "Shin'etsu Main Line",
    "水郡線": "Suigun Line",
    "水戸線": "Mito Line",
    "日光線": "Nikko Line",
    "両毛線": "Ryomo Line",
    "上越線": "Joetsu Line",
    "小海線": "Koumi Line",
    "身延線": "Minobu Line",
    "白新線": "Hakushin Line",
    "飯山線": "Iiyama Line",
    "越後線": "Echigo Line",
    "大糸線": "Oito Line",
    "弥彦線": "Yahiko Line",
    "篠ノ井線": "Shinonoi Line",
    "高山本線": "Takayama Main Line",
    "城端線": "Johana Line",
    "氷見線": "Himi Line",
    "七尾線": "Nanao Line",
    "越美北線": "Etsumi-Hoku Line",
    "小浜線": "Obama Line",
    "伊東線": "Ito Line",
    "御殿場線": "Gotemba Line",
    "武豊線": "Taketoyo Line",
    "太多線": "Taita Line",
    "紀勢本線": "Kisei Main Line",
    "草津線": "Kusatsu Line",
    "参宮線": "Sangu Line",
    "名松線": "Meisho Line",
    "琵琶湖線": "Biwako Line",
    "JR京都線": "JR Kyoto Line",
    "京都線": "JR Kyoto Line",
    "湖西線": "Kosei Line",
    "大和路線": "Yamatoji Line",
    "嵯峨野線": "Sagano Line",
    "片町線": "Katamachi Line",
    "奈良線": "Nara Line (JR West)",
    "舞鶴線": "Maizuru Line",
    "大阪環状線": "Osaka Loop Line",
    "桜島線": "Sakurajima Line",
    "JR東西線": "JR Tozai Line",
    "東西線": "JR Tozai Line",
    "関西空港線": "Kansai Airport Line",
    "福知山線": "Fukuchiyama Line",
    "赤穂線": "Ako Line",
    "加古川線": "Kakogawa Line",
    "播但線": "Bantan Line",
    "和歌山線": "Wakayama Line",
    "桜井線": "Sakurai Line",
    "おおさか東線": "Osaka Higashi Line",
    "伯備線": "Hakubi Line",
    "因美線": "Inbi Line",
    "境線": "Sakai Line",
    "木次線": "Kisuki Line",
    "山口線": "Yamaguchi Line",
    "宇野線": "Uno Line",
    "瀬戸大橋線": "Seto-Ohashi Line",
    "吉備線": "Kibi Line",
    "芸備線": "Geibi Line",
    "津山線": "Tsuyama Line",
    "呉線": "Kure Line",
    "可部線": "Kabe Line",
    "福塩線": "Fukuen Line",
    "宇部線": "Ube Line",
    "美祢線": "Mine Line",
    "小野田線": "Onoda Line",
    "岩徳線": "Gantoku Line",
    "土讃線": "Dosan Line",
    "高徳線": "Kotoku Line",
    "徳島線": "Tokushima Line",
    "牟岐線": "Mugi Line",
    "鳴門線": "Naruto Line",
    "予讃線": "Yosan Line",
    "予土線": "Yodo Line",
    "博多南線": "Hakata-Minami Line",
    "福北ゆたか線": "Fukuhoku Yutaka Line",
    "筑豊本線": "Chikuho Main Line",
    "久大本線": "Kyudai Main Line",
    "日田彦山線": "Hitahikosan Line",
    "後藤寺線": "Gotoji Line",
    "香椎線": "Kashii Line",
    "佐世保線": "Sasebo Line",
    "唐津線": "Karatsu Line",
    "大村線": "Omura Line",
    "豊肥本線": "Hohi Main Line",
    "宮崎空港線": "Miyazaki Kuko Line",
    "日南線": "Nichinan Line",
    "指宿枕崎線": "Ibusuki Makurazaki Line",
    "東武東上本線": "Tobu Tojo Line",
    "東武伊勢崎線": "Tobu Isesaki Line",
    "東武日光線": "Tobu Nikko Line",
    "東武野田線": "Tobu Urban Park Line",
    "東武亀戸線": "Tobu Kameido Line",
    "東武大師線": "Tobu Daishi Line",
    "東武越生線": "Tobu Ogose Line",
    "東武宇都宮線": "Tobu Utsunomiya Line",
    "東武鬼怒川線": "Tobu Kinugawa Line",
    "東武佐野線": "Tobu Sano Line",
    "東武桐生線": "Tobu Kiryu Line",
    "東武小泉線": "Tobu Koizumi Line",
    "西武池袋線": "Seibu Ikebukuro Line",
    "西武秩父線": "Seibu Chichibu Line",
    "西武有楽町線": "Seibu Yurakucho Line",
    "西武豊島線": "Seibu Toshima Line",
    "西武狭山線": "Seibu Sayama Line",
    "西武山口線": "Seibu Yamaguchi Line",
    "西武新宿線": "Seibu Shinjuku Line",
    "西武拝島線": "Seibu Haijima Line",
    "西武西武園線": "Seibu Seibu-en Line",
    "西武国分寺線": "Seibu Kokubunji Line",
    "西武多摩湖線": "Seibu Tamako Line",
    "西武多摩川線": "Seibu Tamagawa Line",
    "京成本線": "Keisei Main Line",
    "京成押上線": "Keisei Oshiage Line",
    "京成金町線": "Keisei Kanamachi Line",
    "京成千葉線": "Keisei Chiba Line",
    "京成千原線": "Keisei Chihara Line",
    "京成成田空港線": "Keisei Narita Airport Line",
    "京王線": "Keio Line",
    "京王相模原線": "Keio Sagamihara Line",
    "京王高尾線": "Keio Takao Line",
    "京王競馬場線": "Keio Keibajo Line",
    "京王動物園線": "Keio Dobutsuen Line",
    "京王井の頭線": "Keio Inokashira Line",
    "京王新線": "Keio New Line",
    "小田急小田原線": "Odakyu Odawara Line",
    "小田急江ノ島線": "Odakyu Enoshima Line",
    "小田急多摩線": "Odakyu Tama Line",
    "東急東横線": "Tokyu Toyoko Line",
    "東急目黒線": "Tokyu Meguro Line",
    "東急田園都市線": "Tokyu Den-en-toshi Line",
    "東急大井町線": "Tokyu Oimachi Line",
    "東急池上線": "Tokyu Ikegami Line",
    "東急多摩川線": "Tokyu Tamagawa Line",
    "東急世田谷線": "Tokyu Setagaya Line",
    "東急こどもの国線": "Yokohama Minatomirai Railway Kodomonokuni Line",
    "京急本線": "Keikyu Main Line",
    "京急空港線": "Keikyu Airport Line",
    "京急大師線": "Keikyu Daishi Line",
    "京急逗子線": "Keikyu Zushi Line",
    "京急久里浜線": "Keikyu Kurihama Line",
    "東京メトロ銀座線": "Tokyo Metro Ginza Line",
    "東京メトロ丸ノ内線": "Tokyo Metro Marunouchi Line",
    "東京メトロ日比谷線": "Tokyo Metro Hibiya Line",
    "東京メトロ東西線": "Tokyo Metro Tozai Line",
    "東京メトロ千代田線": "Tokyo Metro Chiyoda Line",
    "東京メトロ有楽町線": "Tokyo Metro Yurakucho Line",
    "東京メトロ半蔵門線": "Tokyo Metro Hanzomon Line",
    "東京メトロ南北線": "Tokyo Metro Namboku Line",
    "東京メトロ副都心線": "Tokyo Metro Fukutoshin Line",
    "相鉄本線": "Sagami Railway Main Line",
    "相鉄いずみ野線": "Sagami Railway Izumino Line",
    "名鉄名古屋本線": "Meitetsu Nagoya Main Line",
    "名鉄豊川線": "Meitetsu Toyokawa Line",
    "名鉄西尾線": "Meitetsu Nishio Line",
    "名鉄蒲郡線": "Meitetsu Gamagori Line",
    "名鉄三河線": "Meitetsu Mikawa Line",
    "名鉄豊田線": "Meitetsu Toyota Line",
    "名鉄空港線": "Meitetsu Airport Line",
    "名鉄常滑線": "Meitetsu Tokoname Line",
    "名鉄河和線": "Meitetsu Kowa Line",
    "名鉄知多新線": "Meitetsu Chita New Line",
    "名鉄築港線": "Meitetsu Chikko Line",
    "名鉄瀬戸線": "Meitetsu Seto Line",
    "名鉄津島線": "Meitetsu Tsushima Line",
    "名鉄尾西線": "Meitetsu Bisai Line",
    "名鉄犬山線": "Meitetsu Inuyama Line",
    "名鉄各務原線": "Meitetsu Kakamigahara Line",
    "名鉄広見線": "Meitetsu Hiromi Line",
    "名鉄小牧線": "Meitetsu Komaki Line",
    "名鉄竹鼻線": "Meitetsu Takehana Line",
    "名鉄羽島線": "Meitetsu Hashima Line",
    "近鉄難波線": "Kintetsu Namba Line",
    "近鉄橿原線": "Kashihara Line",
    "近鉄南大阪線": "Minami Osaka Line",
    "近鉄大阪線": "Osaka Line",
    "近鉄吉野線": "Yoshino Line",
    "近鉄湯の山線": "Yunoyama Line",
    "近鉄山田線": "Yamada Line (Kintetsu)",
    "近鉄鳥羽線": "Toba Line",
    "近鉄天理線": "Tenri Line",
    "近鉄道明寺線": "Domyoji Line",
    "四日市あすなろう鉄道内部線": "Yokkaichi Asunarou Railway Utsube Line",
    "四日市あすなろう鉄道八王子線": "Yokkaichi Asunarou Railway Hachioji Line",
    "近鉄志摩線": "Shima Line",
    "近鉄生駒線": "Ikoma Line",
    "近鉄田原本線": "Tawaramoto Line",
    "近鉄御所線": "Gose Line",
    "近鉄鈴鹿線": "Suzuka Line",
    "近鉄奈良線": "Nara Line (Kintetsu)",
    "近鉄信貴線": "Shigi Line",
    "近鉄長野線": "Nagano Line (Kintetsu)",
    "近鉄けいはんな線": "Keihanna Line",
    "近鉄西信貴鋼索線": "Nishi-Shigi Cable Line",
    "近鉄京都線": "Kyoto Line (Kintetsu)",
    "近鉄生駒鋼索線": "Ikoma Cable Line",
    "近鉄名古屋線": "Nagoya Line (Kintetsu)",
    "南海本線": "Nankai Main Line",
    "南海空港線": "Nankai Airport Line",
    "南海和歌山港線": "Wakayamako Line",
    "南海高師浜線": "Takashinohama Line",
    "南海加太線": "Kada Line",
    "南海多奈川線": "Tanagawa Line",
    "南海高野線": "Koya Line",
    "京阪本線": "Keihan Main Line",
    "京阪宇治線": "Keihan Uji Line",
    "京阪交野線": "Keihan Katano Line",
    "京阪鴨東線": "Keihan Oto Line",
    "京阪鋼索線": "Keihan Cable Line",
    "京阪石山坂本線": "Keihan Ishiyama Sakamoto Line",
    "京阪京津線": "Keihan Keishin Line",
    "京阪中之島線": "Keihan Nakanoshima Line",
    "阪急神戸本線": "Hankyu Kobe Main Line",
    "阪急宝塚本線": "Hankyu Takarazuka Main Line",
    "阪急京都本線": "Hankyu Kyoto Main Line",
    "阪急今津線": "Hankyu Imazu Line",
    "阪急甲陽線": "Hankyu Koyo Line",
    "阪急伊丹線": "Hankyu Itami Line",
    "阪急箕面線": "Hankyu Minoo Line",
    "阪急千里線": "Hankyu Senri Line",
    "阪急嵐山線": "Hankyu Arashiyama Line",
    "阪神本線": "Hanshin Main Line",
    "阪神なんば線": "Hanshin Namba Line",
    "阪神武庫川線": "Hanshin Mukogawa Line",
    "西鉄天神大牟田線": "Nishitetsu Tenjin Omuta Line",
    "西鉄太宰府線": "Dazaifu Line",
    "西鉄甘木線": "Nishitetsu Amagi Line",
    "西鉄貝塚線": "Nishitetsu Kaizuka Line",
    "札幌市営地下鉄東西線": "Tozai Line (Sapporo)",
    "札幌市営地下鉄南北線": "Namboku Line (Sapporo)",
    "札幌市営地下鉄東豊線": "Toho Line",
    "津軽鉄道線": "Tsugaru Railway",
    "弘南鉄道弘南線": "Kōnan Line",
    "弘南鉄道大鰐線": "Konan Railway Owani Line",
    "いわて銀河鉄道線": "Iwate Galaxy Railway Line",
    "青い森鉄道線": "Aoimori Railway Line",
    "秋田内陸縦貫鉄道秋田内陸線": "Akita Nairiku Line",
    "由利高原鉄道鳥海山ろく線": "Chokai Sanroku Line",
    "山形鉄道フラワー長井線": "Flower Nagai Line",
    "阿武隈急行線": "Abukuma Express Line",
    "福島交通飯坂線": "Fukushima Kotsu Iizaka Line",
    "会津鉄道会津線": "Aizu Line",
    "仙台空港鉄道仙台空港線": "Sendai Airport Line",
    "都営地下鉄大江戸線": "Toei Oedo Line",
    "都営地下鉄浅草線": "Toei Asakusa Line",
    "都営地下鉄三田線": "Toei Mita Line",
    "都営地下鉄新宿線": "Toei Shinjuku Line",
    "都電荒川線": "Toden Arakawa Line",
    "東京都交通局日暮里・舎人ライナー": "Nippori-Toneri Liner",
    "秩父鉄道秩父本線": "Chichibu Main Line",
    "埼玉高速鉄道線": "Saitama Rapid Railway Line",
    "いすみ鉄道いすみ線": "Isumi Line",
    "首都圏新都市鉄道つくばエクスプレス": "Tsukuba Express",
    "横浜高速鉄道みなとみらい線": "Minatomirai Line",
    "ゆりかもめ東京臨海新交通臨海線": "Yurikamome",
    "わたらせ渓谷鐵道わたらせ渓谷線": "Watarase Keikoku Line",
    "山万ユーカリが丘線": "Yamaman Yukarigaoka Line",
    "伊豆箱根鉄道大雄山線": "Daiyuzan Line",
    "ひたちなか海浜鉄道湊線": "Minato Line",
    "横浜市営地下鉄ブルーライン": "Yokohama Municipal Subway Blue Line",
    "横浜市営地下鉄グリーンライン": "Yokohama Municipal Subway Green Line",
    "横浜シーサイドライン金沢シーサイドライン": "Kanazawa Seaside Line",
    "関東鉄道常総線": "Joso Line",
    "関東鉄道竜ヶ崎線": "Ryugasaki Line",
    "埼玉新都市交通伊奈線": "New Shuttle",
    "鹿島臨海鉄道大洗鹿島線": "Oarai Kashima Line",
    "芝山鉄道線": "Shibayama Railway Line",
    "小湊鉄道線": "Kominato Line",
    "上信電鉄上信線": "Jōshin Dentetsu Line",
    "上毛電気鉄道上毛線": "Jomo Line",
    "新京成電鉄新京成線": "Shin-Keisei Line",
    "真岡鐵道真岡線": "Mooka Line",
    "流鉄流山線": "Nagareyama Line",
    "多摩都市モノレール線": "Tama Toshi Monorail Line",
    "東京臨海高速鉄道りんかい線": "Rinkai Line",
    "東葉高速鉄道東葉高速線": "Tōyō Rapid Line",
    "箱根登山鉄道鉄道線": "Hakone Tozan Line",
    "北総鉄道北総線": "Hokusō Line",
    "野岩鉄道会津鬼怒川線": "Aizu Kinugawa Line",
    "箱根登山鉄道鋼索線": "Hakone Tozan Cable Car",
    "富士急行線": "Fujikyuko Line",
    "北越急行ほくほく線": "Hokuhoku Line",
    "しなの鉄道線": "Shinano Railway Line",
    "しなの鉄道北しなの線": "Kita-Shinano Line",
    "上田電鉄別所線": "Ueda Electric Railway Bessho Line",
    "アルピコ交通上高地線": "Kamikochi Line",
    "万葉線": "Manyosen",
    "富山ライトレール富山港線": "Toyama Light Rail Toyamako Line",
    "北陸鉄道石川線": "Hokuriku Railroad Ishikawa Line",
    "北陸鉄道浅野川線": "Hokuriku Railroad Asanogawa Line",
    "えちぜん鉄道勝山永平寺線": "Katsuyama Eiheiji Line",
    "えちぜん鉄道三国芦原線": "Mikuni Awara Line",
    "福井鉄道福武線": "Fukui Railway Fukubu Line",
    "伊豆急行線": "Izu Kyuko Line",
    "伊豆箱根鉄道駿豆線": "Izuhakone Railway Sunzu Line",
    "岳南電車岳南線": "Gakunan Line",
    "静岡鉄道静岡清水線": "Shizuoka Railway Shizuoka–Shimizu Line",
    "天竜浜名湖鉄道天竜浜名湖線": "Tenryū Hamanako Line",
    "遠州鉄道鉄道線": "Enshu Railway Line",
    "大井川鐵道大井川本線": "Oigawa Railway Oigawa Main Line",
    "大井川鐵道井川線": "Oigawa Railway Ikawa Line",
    "名古屋臨海高速鉄道あおなみ線": "Aonami Line",
    "東海交通事業城北線": "Tokai Transport Service Johoku Line",
    "愛知環状鉄道線": "Aichi Loop Line",
    "愛知高速交通東部丘陵線": "Linimo",
    "名古屋市営地下鉄東山線": "Higashiyama Line",
    "名古屋市営地下鉄名城線": "Meijo Line",
    "名古屋市営地下鉄名港線": "Meiko Line",
    "名古屋市営地下鉄鶴舞線": "Tsurumai Line",
    "名古屋市営地下鉄桜通線": "Sakura-dori Line",
    "名古屋市営地下鉄上飯田線": "Kamiiida Line",
    "豊橋鉄道渥美線": "Toyohashi Railroad Atsumi Line",
    "名古屋ガイドウェイバスガイドウェイバス志段味線": "Yutorito Line",
    "明知鉄道明知線": "Akechi Line",
    "長良川鉄道越美南線": "Etsumi-Nan Line",
    "樽見鉄道樽見線": "Tarumi Line",
    "三岐鉄道北勢線": "Sangi Railway Hokusei Line",
    "伊勢鉄道伊勢線": "Ise Line",
    "伊賀鉄道伊賀線": "Iga Line",
    "養老鉄道養老線": "Yōrō Line",
    "近江鉄道本線": "Ohmi Railway Main Line",
    "近江鉄道多賀線": "Ohmi Railway Taga Line",
    "近江鉄道八日市線": "Ohmi Railway Yokaichi Line",
    "嵯峨野観光鉄道嵯峨野観光線": "Sagano Scenic Line",
    "京都丹後鉄道宮福線": "Miyafuku Line",
    "京都市営地下鉄烏丸線": "Karasuma Line",
    "京都市営地下鉄東西線": "Tozai Line (Kyoto)",
    "泉北高速鉄道線": "Semboku Rapid Railway",
    "水間鉄道水間線": "Mizuma Line",
    "大阪市高速電気軌道御堂筋線": "Osaka Metro Midosuji Line",
    "大阪市高速電気軌道谷町線": "Osaka Metro Tanimachi Line",
    "大阪市高速電気軌道四つ橋線": "Osaka Metro Yotsubashi Line",
    "大阪市高速電気軌道中央線": "Osaka Metro Chuo Line",
    "大阪市高速電気軌道千日前線": "Osaka Metro Sennichimae Line",
    "大阪市高速電気軌道堺筋線": "Osaka Metro Sakaisuji Line",
    "大阪市高速電気軌道長堀鶴見緑地線": "Osaka Metro Nagahori Tsurumi-ryokuchi Line",
    "大阪市高速電気軌道今里筋線": "Osaka Metro Imazatosuji Line",
    "大阪市高速電気軌道南港ポートタウン線": "Osaka Metro Nanko Port Town Line",
    "大阪高速鉄道大阪モノレール線": "Osaka Monorail Main Line",
    "神戸電鉄有馬線": "Shintetsu Arima Line",
    "神戸電鉄三田線": "Shintetsu Sanda Line",
    "神戸電鉄公園都市線": "Shintetsu Koen-Toshi Line",
    "神戸電鉄粟生線": "Shintetsu Ao Line",
    "北条鉄道北条線": "Hōjō Line",
    "神戸市営地下鉄海岸線": "Kaigan Line",
    "神戸新交通ポートアイランド線": "Port Island Line",
    "神戸新交通六甲アイランド線": "Rokko Island Line",
    "紀州鉄道線": "Kishu Railway Line",
    "和歌山電鐵貴志川線": "Kishigawa Line",
    "若桜鉄道若桜線": "Wakasa Line",
    "井原鉄道井原線": "Ibara Line",
    "スカイレールサービス広島短距離交通瀬野線": "Skyrail Midorizaka Line",
    "広島高速交通広島新交通1号線": "Astram Line",
    "錦川鉄道錦川清流線": "Nishikigawa Seiryu Line",
    "土佐くろしお鉄道中村線": "Nakamura Line",
    "土佐くろしお鉄道宿毛線": "Sukumo Line",
    "土佐くろしお鉄道阿佐線": "Tosa Kuroshio Railway Asa Line",
    "とさでん交通伊野線": "Tosaden Kotsu Ino Line",
    "とさでん交通桟橋線": "Tosaden Kotsu Sanbashi Line",
    "甘木鉄道甘木線": "Amagi Line",
    "筑豊電気鉄道線": "Chikuho Electric Railroad Line",
    "島原鉄道線": "Shimabara Railway Line",
    "南阿蘇鉄道高森線": "Minamiaso Railway Takamori Line",
    "くま川鉄道湯前線": "Yunomae Line",
    "沖縄都市モノレール線": "Okinawa Monorail",
    "明寺線": "Domyoji Line",
    "内部線": "Yokkaichi Asunarou Railway Utsube Line",
    "八王子線": "Yokkaichi Asunarou Railway Hachioji Line",
    "弘南線": "Kōnan Line",
    "大鰐線": "Konan Railway Owani Line",
    "秋田内陸線": "Akita Nairiku Line",
    "鳥海山ろく線": "Chokai Sanroku Line",
    "フラワー長井線": "Flower Nagai Line",
    "会津線": "Aizu Line",
    "仙台空港線": "Sendai Airport Line",
    "秩父本線": "Chichibu Main Line",
    "いすみ線": "Isumi Line",
    "みなとみらい線": "Minatomirai Line",
    "わたらせ渓谷線": "Watarase Keikoku Line",
    "大雄山線": "Daiyuzan Line",
    "湊線": "Minato Line",
    "常総線": "Joso Line",
    "竜ヶ崎線": "Ryugasaki Line",
    "大洗鹿島線": "Oarai Kashima Line",
    "上信線": "Jōshin Dentetsu Line",
    "上毛線": "Jomo Line",
    "新京成線": "Shin-Keisei Line",
    "真岡線": "Mooka Line",
    "りんかい線": "Rinkai Line",
    "東葉高速線": "Tōyō Rapid Line",
    "鉄道線": "Hakone Tozan Line",
    "北総線": "Hokusō Line",
    "会津鬼怒川線": "Aizu Kinugawa Line",
    "鋼索線": "Hakone Tozan Cable Car",
    "ほくほく線": "Hokuhoku Line",
    "北しなの線": "Kita-Shinano Line",
    "別所線": "Ueda Electric Railway Bessho Line",
    "石川線": "Hokuriku Railroad Ishikawa Line",
    "浅野川線": "Hokuriku Railroad Asanogawa Line",
    "勝山永平寺線": "Katsuyama Eiheiji Line",
    "三国芦原線": "Mikuni Awara Line",
    "福武線": "Fukui Railway Fukubu Line",
    "駿豆線": "Izuhakone Railway Sunzu Line",
    "静岡清水線": "Shizuoka Railway Shizuoka–Shimizu Line",
    "天竜浜名湖線": "Tenryū Hamanako Line",
    "大井川本線": "Oigawa Railway Oigawa Main Line",
    "井川線": "Oigawa Railway Ikawa Line",
    "あおなみ線": "Aonami Line",
    "渥美線": "Toyohashi Railroad Atsumi Line",
    "明知線": "Akechi Line",
    "越美南線": "Etsumi-Nan Line",
    "樽見線": "Tarumi Line",
    "北勢線": "Sangi Railway Hokusei Line",
    "伊勢線": "Ise Line",
    "伊賀線": "Iga Line",
    "養老線": "Yōrō Line",
    "本線": "Ohmi Railway Main Line",
    "多賀線": "Ohmi Railway Taga Line",
    "八日市線": "Ohmi Railway Yokaichi Line",
    "嵯峨野観光線": "Sagano Scenic Line",
    "宮福線": "Miyafuku Line",
    "水間線": "Mizuma Line",
    "大阪モノレール線": "Osaka Monorail Main Line",
    "有馬線": "Shintetsu Arima Line",
    "三田線": "Shintetsu Sanda Line",
    "公園都市線": "Shintetsu Koen-Toshi Line",
    "粟生線": "Shintetsu Ao Line",
    "北条線": "Hōjō Line",
    "貴志川線": "Kishigawa Line",
    "若桜線": "Wakasa Line",
    "井原線": "Ibara Line",
    "錦川清流線": "Nishikigawa Seiryu Line",
    "中村線": "Nakamura Line",
    "宿毛線": "Sukumo Line",
    "阿佐線": "Tosa Kuroshio Railway Asa Line",
    "甘木線": "Amagi Line",
    "高森線": "Minamiaso Railway Takamori Line",
    "湯前線": "Yunomae Line",
    "山形線": "Yamagata Line",
    "岳南線": "Gakunan Line",
    "三岐線": "Sangi Line",
    "三岐鉄道三岐線": "Sangi Line",
    "智頭線": "Chizu Line",
    "智頭急行智頭線": "Chizu Line"
};
