'use client';
import { TripEvent, TransportationMethod, EventLocation } from '@pplaner/shared';
import { MainCategory, SubCategory, CATEGORY_MAP } from '@pplaner/shared';
import { motion, AnimatePresence } from 'framer-motion';
import { useState, useCallback, useEffect } from 'react';
import { useTripStore } from '@pplaner/shared';
import { Calendar } from 'lucide-react';

interface EventEditorModalProps {
    event?: Partial<TripEvent>;
    dayIdx?: number;
    isOpen: boolean;
    onClose: () => void;
    onSave: (event: Partial<TripEvent> | Partial<TripEvent>[]) => void;
    onNavigateToSection?: (section: string) => void;
}

const formatDateWithDay = (dateStr?: string) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    const year = date.getFullYear();
    const month = date.getMonth() + 1;
    const day = date.getDate();
    const dayOfWeek = ['일', '월', '화', '수', '목', '금', '토'][date.getDay()];
    return `${year}년 ${month}월 ${day}일 (${dayOfWeek})`;
};




const TRANSPORT_METHODS: { id: TransportationMethod; label: string; icon: string }[] = [
    { id: 'walking', label: '도보', icon: 'directions_walk' },
    { id: 'bus', label: '버스', icon: 'directions_bus' },
    { id: 'train', label: '열차', icon: 'directions_railway' },
    { id: 'taxi', label: '택시', icon: 'local_taxi' },
    { id: 'bicycle', label: '자전거', icon: 'directions_bike' },
    { id: 'flight', label: '항공', icon: 'flight' },
    { id: 'ship', label: '선박', icon: 'directions_boat' },
];

import SimpleEventEditor from './SimpleEventEditor';

export default function EventEditorModal({ event, dayIdx, isOpen, onClose, onSave, onNavigateToSection }: EventEditorModalProps) {
    const { currentTrip: trip } = useTripStore();
    const targetDay = (dayIdx !== undefined && trip?.dailyTimeline) ? trip.dailyTimeline[dayIdx] : null;
    const dateStr = targetDay?.date;

    // ... existing specialized states for flight
    const [isInternational, setIsInternational] = useState(event?.isInternational ?? true);
    const [prepDuration, setPrepDuration] = useState<number>(
        event?.prepDurationMinutes ?? (isInternational ? 120 : 60)
    );
    const [entryDuration, setEntryDuration] = useState<number>(
        event?.entryDurationMinutes ?? (isInternational ? 60 : 30)
    );

    useEffect(() => {
        if (event?.prepDurationMinutes !== undefined) setPrepDuration(event.prepDurationMinutes);
        if (event?.entryDurationMinutes !== undefined) setEntryDuration(event.entryDurationMinutes);
        if (event?.isInternational !== undefined) setIsInternational(event.isInternational);
    }, [event]);

    // Flight segment detection
    const isDepartureFlightSegment = event?.id?.endsWith('-prep') && event?.isAutoGenerated === true;
    const isArrivalFlightSegment = event?.id?.endsWith('-arr') && event?.isAutoGenerated === true;
    const isAutoFlight = !!event?.isAutoGenerated && (event?.autoGeneratedType === 'flight' || event?.autoGeneratedType === 'flight-segment');

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[150] flex items-center justify-center">
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-slate-950/40 backdrop-blur-[2px]"
                    />

                    {/* Modal Content */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, y: 30 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.9, y: 30 }}
                        transition={{ 
                            type: 'spring', 
                            damping: 28, 
                            stiffness: 260,
                            mass: 0.9
                        }}
                        className="relative w-[calc(100%-48px)] max-w-3xl h-[calc(100%-80px)] max-h-[850px] bg-white dark:bg-slate-900 rounded-[32px] shadow-[0_32px_80px_-20px_rgba(0,0,0,0.4)] border border-slate-200/50 dark:border-slate-800 overflow-hidden flex flex-col z-[151]"
                    >
                        {!isAutoFlight ? (
                            <SimpleEventEditor 
                                event={event} 
                                dayIdx={dayIdx}
                                date={dateStr}
                                onSave={onSave} 
                                onClose={onClose} 
                            />
                        ) : (
                            <>
                                {/* Header */}
                                <div className="p-6 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between bg-slate-50/50 dark:bg-slate-800/20">
                                    <div className="flex flex-col gap-1">
                                        <h3 className="text-xl font-black text-slate-900 dark:text-white flex items-center gap-2">
                                            <span className="material-symbols-rounded text-primary">edit_calendar</span>
                                            항공편 자동 수속 일정
                                        </h3>
                                        {(dateStr || dayIdx !== undefined) && (
                                            <div className="flex items-center gap-1.5">
                                                <Calendar className="w-3.5 h-3.5 text-primary" />
                                                <span className="text-sm font-black text-primary uppercase tracking-tight">
                                                    {dayIdx !== undefined ? `Day ${dayIdx + 1}` : ''}
                                                    {dayIdx !== undefined && dateStr ? ' • ' : ''}
                                                    {formatDateWithDay(dateStr)}
                                                </span>
                                            </div>
                                        )}
                                    </div>
                                    <button onClick={onClose} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition-colors">
                                        <span className="material-symbols-rounded text-slate-400">close</span>
                                    </button>
                                </div>

                                {/* Content */}
                                <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
                                    <div className="space-y-6">
                                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">위치 정보</label>
                                        <div className="p-6 bg-sky-50 dark:bg-sky-900/10 rounded-[28px] border border-sky-100 dark:border-sky-800/50 space-y-6">
                                            <div className="flex items-center gap-3">
                                                <div className="w-12 h-12 rounded-2xl bg-sky-500 flex items-center justify-center text-white shadow-lg shadow-sky-500/20">
                                                    <span className="material-symbols-rounded text-2xl">flight</span>
                                                </div>
                                                <div>
                                                    <h4 className="text-base font-black text-slate-900 dark:text-white">항공편 상세 정보</h4>
                                                    <p className="text-[10px] font-bold text-sky-500 uppercase tracking-widest">자동 생성된 일정입니다</p>
                                                </div>
                                            </div>
                                            <div className="p-5 bg-white dark:bg-slate-900/50 rounded-2xl border border-sky-100/50 dark:border-sky-800/30">
                                                <div className="flex items-center gap-4">
                                                    <span className="material-symbols-rounded text-slate-400">location_on</span>
                                                    <div className="flex-1">
                                                        <p className="text-xs font-bold text-slate-400 uppercase tracking-tighter mb-0.5">공항</p>
                                                        <p className="text-sm font-black text-slate-900 dark:text-white italic">{event?.location?.name}</p>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            {/* Duration Edit Area */}
                                            <div className="p-6 bg-white dark:bg-slate-900 rounded-[28px] border border-sky-100 dark:border-sky-800 shadow-sm space-y-6">
                                                <div className="flex items-center justify-between">
                                                    <div className="flex items-center gap-3">
                                                        <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                                                            <span className="material-symbols-rounded text-xl">more_time</span>
                                                        </div>
                                                        <label className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-widest">
                                                            {isDepartureFlightSegment ? '수속 예상 시간 (분)' : '도착 수속 시간 (분)'}
                                                        </label>
                                                    </div>
                                                    <button
                                                        onClick={() => setIsInternational(!isInternational)}
                                                        className={`px-3 py-1.5 rounded-full text-[9px] font-black uppercase tracking-widest transition-all ${isInternational
                                                            ? 'bg-primary text-white shadow-lg shadow-primary/20'
                                                            : 'bg-slate-100 dark:bg-slate-800 text-slate-400'
                                                        }`}
                                                    >
                                                        {isInternational ? '국제선' : '국내선'}
                                                    </button>
                                                </div>

                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                    <div className="space-y-4">
                                                        <div className="relative">
                                                            <input
                                                                type="number"
                                                                value={isDepartureFlightSegment ? prepDuration : entryDuration}
                                                                onChange={(e) => {
                                                                    const val = parseInt(e.target.value) || 0;
                                                                    if (isDepartureFlightSegment) setPrepDuration(val);
                                                                    else setEntryDuration(val);
                                                                }}
                                                                className="w-full bg-slate-50 dark:bg-slate-800 border-2 border-transparent focus:border-primary/30 rounded-xl text-2xl font-black p-4 pr-14 outline-none transition-all"
                                                            />
                                                            <span className="absolute right-6 top-1/2 -translate-y-1/2 text-xs font-black text-slate-300">MIN</span>
                                                        </div>
                                                        
                                                        <div className="flex gap-2">
                                                            {[30, 60, 90, 120, 180].map(mins => (
                                                                <button
                                                                    key={mins}
                                                                    onClick={() => isDepartureFlightSegment ? setPrepDuration(mins) : setEntryDuration(mins)}
                                                                    className={`flex-1 py-2 rounded-lg text-[10px] font-bold transition-all ${
                                                                        (isDepartureFlightSegment ? prepDuration : entryDuration) === mins
                                                                            ? 'bg-primary text-white'
                                                                            : 'bg-slate-50 dark:bg-slate-800 text-slate-400 hover:bg-slate-100'
                                                                    }`}
                                                                >
                                                                    {mins >= 60 ? `${mins/60}h` : `${mins}m`}
                                                                </button>
                                                            ))}
                                                        </div>
                                                    </div>

                                                    <div className="p-6 bg-slate-50 dark:bg-slate-800/50 rounded-2xl border border-slate-200 dark:border-slate-800 flex flex-col justify-center gap-2">
                                                        <div className="flex items-center justify-between text-[10px] font-black text-slate-400 uppercase tracking-widest">
                                                            <span>예상 {isDepartureFlightSegment ? '수속 시작' : '수속 종료'}</span>
                                                            <span className="text-primary">{isDepartureFlightSegment ? '이륙 시간 (고정)' : '착륙 시간 (고정)'}</span>
                                                        </div>
                                                        <div className="flex items-center gap-4">
                                                            <div className="flex-1 text-center">
                                                                <p className="text-2xl font-black text-slate-900 dark:text-white tabular-nums">
                                                                    {isDepartureFlightSegment 
                                                                        ? (() => {
                                                                            const anchor = event?.endTime || '00:00';
                                                                            const [h, m] = anchor.split(':').map(Number);
                                                                            const total = h * 60 + m - prepDuration;
                                                                            const hh = Math.floor((total + 1440) % 1440 / 60);
                                                                            const mm = (total + 1440) % 60;
                                                                            return `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}`;
                                                                        })()
                                                                        : (event?.startTime)
                                                                    }
                                                                </p>
                                                                <p className="text-[9px] font-bold text-slate-400 mt-1 uppercase">Start</p>
                                                            </div>
                                                            <div className="w-px h-8 bg-slate-200 dark:bg-slate-700 opacity-50" />
                                                            <div className="flex-1 text-center">
                                                                <p className="text-2xl font-black text-slate-900 dark:text-white tabular-nums">
                                                                    {isDepartureFlightSegment 
                                                                        ? (event?.endTime)
                                                                        : (() => {
                                                                            const anchor = event?.startTime || '00:00';
                                                                            const [h, m] = anchor.split(':').map(Number);
                                                                            const total = h * 60 + m + entryDuration;
                                                                            const hh = Math.floor((total + 1440) % 1440 / 60);
                                                                            const mm = (total + 1440) % 60;
                                                                            return `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}`;
                                                                        })()
                                                                    }
                                                                </p>
                                                                <p className="text-[9px] font-bold text-slate-400 mt-1 uppercase">End</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <p className="text-[11px] font-medium text-slate-400 italic text-center p-2 leading-relaxed">
                                                    {isDepartureFlightSegment 
                                                        ? `항공편 ${isInternational ? '출발 2시간 전' : '출발 1시간 전'} 권장 시간을 참고하여 조정해 보세요.` 
                                                        : `착륙 후 입국 심사 및 수하물 수령에 소요되는 시간을 설정합니다.`}
                                                </p>
                                            </div>

                                            <button
                                                onClick={() => {
                                                    onNavigateToSection?.('transport');
                                                    onClose();
                                                }}
                                                className="w-full py-4 bg-sky-500 hover:bg-sky-600 text-white rounded-2xl text-[11px] font-black uppercase tracking-widest shadow-xl shadow-sky-500/20 transition-all flex items-center justify-center gap-2 group"
                                            >
                                                <span className="material-symbols-rounded text-sm transition-transform group-hover:translate-x-1">rocket_launch</span>
                                                항공편 수정으로 이동
                                            </button>
                                        </div>
                                    </div>
                                </div>

                                {/* Footer */}
                                <div className="p-6 border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 flex items-center gap-4">
                                    <button
                                        onClick={onClose}
                                        className="flex-1 py-4 text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
                                    >
                                        취소하기
                                    </button>
                                    <button
                                        onClick={() => {
                                            const updates: Partial<TripEvent> = { ...event };
                                            if (isDepartureFlightSegment) updates.prepDurationMinutes = prepDuration;
                                            if (isArrivalFlightSegment) updates.entryDurationMinutes = entryDuration;
                                            updates.isInternational = isInternational;
                                            onSave(updates);
                                            onClose();
                                        }}
                                        className="flex-[2] py-4 bg-primary text-white rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl shadow-primary/20 hover:scale-[1.02] active:scale-[0.98] transition-all"
                                    >
                                        설정 저장하기
                                    </button>
                                </div>
                            </>
                        )}
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
}
