'use client';
import { useTripStore } from '@pplaner/shared';
import { TripEvent, TransportationMethod, TRANSPORT_ICONS, TRANSPORT_LABELS } from '@pplaner/shared';
import { CATEGORY_MAP, MainCategory } from '@pplaner/shared';
import { motion } from 'framer-motion';
import { cn, timeToMinutes } from '@pplaner/shared';
import { useState, useMemo } from 'react';

interface TimelineEventCardProps {
    event: TripEvent;
    prevTransport?: TripEvent['transportToNext'];
    flightIntervals?: { start: string; end: string }[];
    onEdit?: (event: Partial<TripEvent>) => void;
    onDelete?: (eventId: string) => void;
    onUpdateTransport?: (transport: TripEvent['transportToNext']) => void;
    onNavigateToSection?: (section: string) => void;
    onAddComment?: (eventId: string) => void;
    isHighlighted?: boolean;
    dragHandleProps?: Record<string, any>;
    isDragging?: boolean;
}



const ACC_COLORS: Record<string, string> = {
    'check-in': 'bg-amber-50/50 dark:bg-amber-900/10 border-amber-200/40 dark:border-amber-800/40 text-amber-700 dark:text-amber-400 border-l-amber-400',
    'check-out': 'bg-orange-50/50 dark:bg-orange-900/10 border-orange-200/40 dark:border-orange-800/40 text-orange-700 dark:text-orange-400 border-l-orange-400',
};

export default function TimelineEventCard({ 
    event, 
    prevTransport, 
    flightIntervals,
    onEdit, 
    onDelete,
    onUpdateTransport,
    onNavigateToSection,
    onAddComment,
    isHighlighted,
    dragHandleProps,
    isDragging
}: TimelineEventCardProps) {
    const isFixed = event.isFixedTime;
    const isAuto = event.isAutoGenerated;
    const updateAccommodation = useTripStore(state => state.updateAccommodation);
    const comments = useTripStore(state => state.comments);

    const eventComments = useMemo(() => {
        return comments.filter(c => c.targetType === 'event' && c.targetId === event.id);
    }, [comments, event.id]);

    const resolvedCount = useMemo(() => eventComments.filter(c => c.isResolved).length, [eventComments]);
    const pendingCount = eventComments.length - resolvedCount;
    
    const duration = useMemo(() => {
        if (event.startTime && event.endTime) {
            const start = timeToMinutes(event.startTime);
            const end = timeToMinutes(event.endTime);
            const diff = end - start;
            if (diff > 0) {
                const h = Math.floor(diff / 60);
                const m = diff % 60;
                return h > 0 ? `${h}시간 ${m > 0 ? `${m}분` : ''}` : `${m}분`;
            }
        }
        return null;
    }, [event.startTime, event.endTime]);

    const isCostUndecided = event.isCostUndecided ?? (event.cost === undefined);

    const [expectedTime, setExpectedTime] = useState(
        event.autoGeneratedType === 'check-in' 
            ? event.expectedCheckInTime || '' 
            : event.expectedCheckOutTime || ''
    );

    const [isEditingTransport, setIsEditingTransport] = useState(false);
    const [tempTransport, setTempTransport] = useState<TripEvent['transportToNext'] | null>(null);

    const isAccEvent = isAuto && (event.autoGeneratedType === 'check-in' || event.autoGeneratedType === 'check-out');
    const isFlightEvent = isAuto && (event.autoGeneratedType === 'flight' || event.autoGeneratedType === 'flight-segment');
    const isReservationEvent = isAuto && event.autoGeneratedType === 'reservation';
    const isFlightSegment = isAuto && event.autoGeneratedType === 'flight-segment';

    const handleTimeChange = (newTime: string) => {
        setExpectedTime(newTime);
        if (event.sourceId) {
            const updates = event.autoGeneratedType === 'check-in' 
                ? { expectedCheckInTime: newTime } 
                : { expectedCheckOutTime: newTime };
            updateAccommodation(event.sourceId, updates);
        }
    };

    const isInvalid = () => {
        if (!expectedTime) return false;
        if (event.autoGeneratedType === 'check-in' && event.checkInTime) {
            return expectedTime < event.checkInTime;
        }
        if (event.autoGeneratedType === 'check-out' && event.checkOutTime) {
            return expectedTime > event.checkOutTime;
        }
        return false;
    };

    const isFlightConflict = () => {
        if (!isAccEvent || !flightIntervals || flightIntervals.length === 0) return false;
        
        // Use expected time if available, otherwise fallback to policy time or default values
        const effectiveTime = expectedTime || 
            (event.autoGeneratedType === 'check-in' ? event.checkInTime : event.checkOutTime) || 
            (event.autoGeneratedType === 'check-in' ? '15:00' : '11:00');
            
        const currentMins = timeToMinutes(effectiveTime);
        return flightIntervals.some(interval => {
            const startMins = timeToMinutes(interval.start);
            const endMins = timeToMinutes(interval.end);
            return currentMins >= startMins && currentMins <= endMins;
        });
    };

    return (
        <div className="relative group">
            {/* Prev Transport Connection */}
            {prevTransport && (
                <div className="ml-[34px] mb-2">
                    {prevTransport.method === 'flight' ? (
                        <div className="flex items-center gap-4 py-2">
                            <div className="w-[3px] h-16 bg-gradient-to-b from-primary/50 to-primary/10 rounded-full relative">
                                {!isAccEvent && (
                                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-6 h-6 rounded-full bg-white dark:bg-slate-900 border-2 border-primary flex items-center justify-center shadow-sm">
                                        <span className="material-symbols-rounded text-[14px] text-primary font-bold">flight</span>
                                    </div>
                                )}
                            </div>
                            <div className="flex flex-col gap-1.5 flex-1 min-w-0">
                                <div className="flex items-center gap-2">
                                    <span className="px-2.5 py-1 bg-primary text-white text-[10px] font-black rounded-lg shadow-lg shadow-primary/20 uppercase tracking-widest">
                                        비행 {Math.floor(prevTransport.durationMinutes / 60)}시간 {prevTransport.durationMinutes % 60}분
                                    </span>
                                    {prevTransport.note && prevTransport.note.includes(' • ') && (
                                        <span className="text-[10px] font-black text-primary bg-amber-50 dark:bg-amber-900/20 px-2 py-1 rounded-lg border border-amber-100 dark:border-amber-800">
                                            {prevTransport.note.split(' • ').slice(-1)}
                                        </span>
                                    )}
                                </div>
                                {prevTransport.note && (
                                    <div className="flex flex-col gap-1 text-[10px] font-bold text-slate-500 ml-1">
                                        {prevTransport.note.split(' • ').map((part, i) => (
                                            <div key={i} className="flex items-start gap-1.5 translate-y-0.5">
                                                <span className="material-symbols-rounded text-[12px] mt-0.5 opacity-60">info</span>
                                                <span className="leading-tight">{part}</span>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        </div>
                    ) : (
                        <div className="flex flex-col gap-2">
                            {isEditingTransport && tempTransport ? (
                                <div className="flex items-center gap-2 p-2 bg-white dark:bg-slate-900 rounded-2xl border-2 border-primary/20 shadow-xl animate-in fade-in slide-in-from-top-2">
                                    <select 
                                        value={tempTransport.method}
                                        onChange={(e) => setTempTransport({...tempTransport, method: e.target.value as TransportationMethod})}
                                        className="bg-slate-100 dark:bg-slate-800 text-[10px] font-black p-1.5 rounded-xl border-none focus:ring-2 focus:ring-primary/20"
                                    >
                                        {Object.entries(TRANSPORT_LABELS).map(([val, label]) => (
                                            <option key={val} value={val}>{label}</option>
                                        ))}
                                    </select>
                                    <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-xl">
                                        <input 
                                            type="number" 
                                            value={tempTransport.durationMinutes}
                                            onChange={(e) => setTempTransport({...tempTransport, durationMinutes: parseInt(e.target.value) || 0})}
                                            className="w-12 bg-transparent text-center text-[10px] font-black border-none focus:ring-0"
                                        />
                                        <span className="text-[9px] font-bold text-slate-400 pr-1">분</span>
                                    </div>
                                    <button 
                                        onClick={() => {
                                            onUpdateTransport?.(tempTransport);
                                            setIsEditingTransport(false);
                                        }}
                                        className="w-8 h-8 flex items-center justify-center bg-primary text-white rounded-xl shadow-lg shadow-primary/20"
                                    >
                                        <span className="material-symbols-rounded text-sm font-black">check</span>
                                    </button>
                                    <button 
                                        onClick={() => setIsEditingTransport(false)}
                                        className="w-8 h-8 flex items-center justify-center bg-slate-100 dark:bg-slate-800 text-slate-400 rounded-xl"
                                    >
                                        <span className="material-symbols-rounded text-sm">close</span>
                                    </button>
                                </div>
                            ) : (
                                <div className="flex items-center gap-3 py-0.5 group/transport">
                                    <div className="w-0.5 h-10 bg-slate-100 dark:bg-slate-800 rounded-full"></div>
                                    <button 
                                        onClick={() => {
                                            setTempTransport(prevTransport);
                                            setIsEditingTransport(true);
                                        }}
                                        className="flex items-center gap-2 px-3 py-1.5 bg-slate-50 dark:bg-slate-800/60 rounded-full border border-slate-200 dark:border-slate-800/80 hover:border-primary/30 hover:bg-white dark:hover:bg-slate-800 transition-all shadow-sm hover:shadow-md group/btn"
                                    >
                                        <span className="material-symbols-rounded text-sm text-slate-400 group-hover/btn:text-primary transition-colors">
                                            {TRANSPORT_ICONS[prevTransport.method]}
                                        </span>
                                        <span className="text-[10px] font-black text-slate-500 uppercase flex items-center gap-1.5">
                                            {TRANSPORT_LABELS[prevTransport.method]} • {prevTransport.durationMinutes}분
                                            <span className="material-symbols-rounded text-[12px] opacity-0 group-hover/btn:opacity-100 transition-opacity">edit</span>
                                        </span>
                                        {prevTransport.note && (
                                            <span className="text-[9px] text-slate-400 font-medium italic border-l border-slate-200 dark:border-slate-700 pl-2">
                                                {prevTransport.note}
                                            </span>
                                        )}
                                    </button>
                                </div>
                            )}
                        </div>
                    )}
                </div>
            )}

            {/* Event Card */}
            <motion.div
                layout
                className={cn(
                    "flex gap-2 p-1.5 rounded-xl border transition-all duration-200",
                    isDragging && "shadow-2xl ring-2 ring-primary/40 opacity-95 scale-[1.02] z-50",
                    isHighlighted 
                        ? 'bg-primary/5 dark:bg-primary/10 border-primary ring-2 ring-primary/20 shadow-lg'
                        : isFlightSegment
                            ? 'bg-transparent border-none !py-1 !px-3'
                            : isAuto && (event.autoGeneratedType === 'flight' || event.autoGeneratedType === 'public-transport')
                                ? 'bg-amber-50/50 dark:bg-amber-900/10 border-amber-200/50 dark:border-amber-800/50 shadow-sm border-l-4 border-l-primary/60'
                                : isAccEvent
                                ? cn(ACC_COLORS[event.autoGeneratedType!], "shadow-sm border-l-4 !p-1 !gap-2 min-h-[48px] hover:shadow-md")
                                : event.isFlexible
                                    ? 'bg-amber-50/30 dark:bg-amber-950/30 border-dashed border-amber-200 dark:border-amber-800/50 hover:bg-white dark:hover:bg-slate-900'
                                    : isFixed
                                        ? 'bg-white dark:bg-slate-900 border-primary/20 shadow-sm'
                                        : 'bg-slate-50 dark:bg-slate-800/40 border-slate-200 dark:border-slate-800 hover:border-primary/30 hover:bg-white dark:hover:bg-slate-800',
                    !isDragging && "group-active:scale-[0.98] group-active:shadow-inner"
                )}
            >
                {/* Drag Handle */}
                {dragHandleProps && !isFlightSegment && (
                    <div 
                        {...dragHandleProps}
                        className="flex flex-col items-center justify-center pl-1 cursor-grab active:cursor-grabbing text-slate-300 hover:text-primary transition-colors"
                    >
                        <span className="material-symbols-rounded text-lg">drag_indicator</span>
                    </div>
                )}

                {/* Time Indicator */}
                <div className={cn(
                    "w-12 flex-shrink-0 flex flex-col items-center justify-center border-r border-slate-200 dark:border-slate-800 pr-2 relative",
                    (isAccEvent || event.isFlexible) && "hidden"
                )}>
                    {event.startTime ? (
                        <>
                            <span className={cn(
                                "text-xs font-black text-slate-900 dark:text-white",
                                isAccEvent && "text-[10px]"
                            )}>{event.startTime}</span>
                            {event.endTime && !isAccEvent && (
                                <span className="text-[9px] text-slate-400 font-bold">~ {event.endTime}</span>
                            )}
                        </>
                    ) : (
                        <div className="flex flex-col items-center">
                            <span className="material-symbols-rounded text-slate-300 text-base">schedule</span>
                            <span className="text-[8px] text-slate-400 font-bold uppercase tracking-tighter">자유 일정</span>
                        </div>
                    )}
                </div>

                <div className={cn(
                    "rounded-lg overflow-hidden flex items-center justify-center border shrink-0",
                    isAccEvent ? 'w-7 h-7' : 'w-10 h-10',
                    isAuto && (event.autoGeneratedType === 'flight' || event.autoGeneratedType === 'public-transport')
                        ? 'bg-sky-100 dark:bg-sky-800 border-sky-200 dark:border-sky-700 font-black'
                        : isAuto && event.autoGeneratedType === 'check-in' ? 'bg-amber-100 border-amber-200'
                        : isAuto && event.autoGeneratedType === 'check-out' ? 'bg-orange-100 border-orange-200'
                        : 'bg-slate-100 dark:bg-slate-800 border-slate-200 dark:border-slate-700'
                )}>
                    {event.imageUrls && event.imageUrls.length > 0 && !isAccEvent ? (
                        <img src={event.imageUrls[0]} alt={event.title} className="w-full h-full object-cover" />
                    ) : (
                        <span className={cn(
                            "material-symbols-rounded",
                            isAccEvent ? "text-sm" : "text-lg",
                            isAuto && (event.autoGeneratedType === 'flight' || event.autoGeneratedType === 'public-transport') ? 'text-primary' :
                            isAuto && event.autoGeneratedType === 'check-in' ? 'text-amber-600' :
                            isAuto && event.autoGeneratedType === 'check-out' ? 'text-orange-600' :
                            'text-primary'
                        )} style={{ color: !isAuto ? CATEGORY_MAP[event.type]?.color : undefined }}>
                            {isAuto && event.autoGeneratedType === 'flight' ? (event.id.endsWith('-prep') ? 'flight_takeoff' : 'flight_land') : 
                             isAuto && event.autoGeneratedType === 'flight-segment' ? 'flight' :
                             isAuto && event.autoGeneratedType === 'public-transport' ? (TRANSPORT_ICONS[event.subCategory as TransportationMethod] || 'directions_transit') :
                             isAuto && event.autoGeneratedType === 'check-in' ? 'login' :
                             isAuto && event.autoGeneratedType === 'check-out' ? 'logout' :
                             (CATEGORY_MAP[event.type]?.icon || 'explore')}
                        </span>
                    )}
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0 flex items-center">
                    <div className="flex items-center justify-between gap-2 xl:gap-4 md:gap-4 w-full">
                        <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-2 mb-0.5">
                                <h4 className={cn(
                                    "font-bold text-slate-900 dark:text-white truncate",
                                    isAccEvent ? "text-xs" : "text-sm",
                                    isFlightSegment && "text-sky-600 dark:text-sky-400 font-black flex items-center gap-2"
                                )}>
                                    {isFlightSegment && <span className="material-symbols-rounded text-[16px]">double_arrow</span>}
                                    {event.isFlexible && <span className="mr-1.5 px-1.5 py-0.5 bg-amber-100 dark:bg-amber-900/40 text-amber-600 dark:text-amber-400 text-[8px] font-black rounded uppercase tracking-tighter shrink-0">자유</span>}
                                    {event.title}
                                </h4>
                                {isAuto && !isFlightSegment && (
                                    <span className="text-[8px] font-black bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5 rounded text-slate-400 uppercase tracking-tighter">자동</span>
                                )}
                            </div>
                            
                            {!isAccEvent && (
                                <div className="flex flex-wrap items-center gap-3 mt-1">
                                    {event.location && (
                                        <div className="flex items-center gap-1 px-2 py-0.5 bg-slate-50 dark:bg-slate-800/50 text-slate-400 rounded-lg border border-slate-200 dark:border-slate-800">
                                            <span className="material-symbols-rounded text-[12px] font-bold">location_on</span>
                                            <span className="text-[9px] font-black uppercase tracking-tight truncate max-w-[120px]">{event.location.name}</span>
                                        </div>
                                    )}
                                    {!isCostUndecided && event.cost !== undefined && event.cost > 0 && (
                                        <div className="flex items-center gap-1 px-2 py-0.5 rounded-lg border bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 dark:text-emerald-400 border-emerald-100 dark:border-emerald-800/50">
                                            <span className="material-symbols-rounded text-[12px] font-bold">payments</span>
                                            <span className="text-[9px] font-black uppercase tracking-tight">
                                                {`${event.currency || 'KRW'} ${event.cost?.toLocaleString()}`}
                                            </span>
                                        </div>
                                    )}
                                    {duration && !isFlightEvent && (
                                        <div className="flex items-center gap-1 px-2 py-0.5 bg-slate-50 dark:bg-slate-800/50 text-slate-400 rounded-lg border border-slate-200 dark:border-slate-800">
                                            <span className="material-symbols-rounded text-[12px] font-bold">timer</span>
                                            <span className="text-[9px] font-black uppercase tracking-tight">{duration}</span>
                                        </div>
                                    )}
                                </div>
                            )}

                            {isAccEvent && (
                                <div className="flex flex-wrap items-center gap-1.5 xl:gap-3 md:gap-3 mt-1">
                                    <div className="flex items-center gap-1.5 px-2 py-0.5 bg-slate-50 dark:bg-slate-800/50 rounded-lg text-[9px] font-bold text-slate-500">
                                        <span className="material-symbols-rounded text-[12px] text-slate-400 font-bold">info</span>
                                        <span className="tracking-tight">
                                            {event.autoGeneratedType === 'check-in' ? '입실 가능' : '퇴실 마감'}: 
                                            <span className="text-slate-900 dark:text-slate-200 font-black ml-1">
                                                {event.autoGeneratedType === 'check-in' 
                                                    ? (event.checkInTime === '' ? '제한 없음' : (event.checkInTime || '15:00')) 
                                                    : (event.checkOutTime === '' ? '제한 없음' : (event.checkOutTime || '11:00'))
                                                }
                                            </span>
                                        </span>
                                    </div>
                                    <p className="text-[10px] text-slate-500 font-medium truncate italic opacity-70">{event.location?.name}</p>
                                    

                                </div>
                            )}

                            {isFlightEvent && (
                                <div className="flex flex-wrap items-center gap-2 mt-1.5">
                                    {!isFlightSegment && (
                                        <div className="flex items-center gap-1.5 px-2 py-0.5 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-100 dark:border-amber-800/50">
                                            <span className="material-symbols-rounded text-[12px] text-primary font-bold">timer</span>
                                            <div className="flex items-center gap-1">
                                                <span className="text-[9px] font-black text-primary/80 dark:text-amber-400 uppercase tracking-widest whitespace-nowrap">
                                                    {event.id.endsWith('-prep') ? '수속 예상' : '도착 수속'}
                                                </span>
                                                <span className="text-[9px] font-black text-primary mx-0.5">
                                                    {event.id.endsWith('-prep') ? (event.prepDurationMinutes || 0) : (event.entryDurationMinutes || 0)}
                                                </span>
                                                <span className="text-[8px] text-primary font-bold">분</span>
                                            </div>
                                        </div>
                                    )}
                                    {event.id.endsWith('-dep') && event.transportToNext?.durationMinutes && (
                                        <div className="flex items-center gap-1 text-[9px] font-bold text-slate-400">
                                            <span className="material-symbols-rounded text-[14px]">flight_takeoff</span>
                                            <span>비행 {Math.floor(event.transportToNext.durationMinutes / 60)}시간 {event.transportToNext.durationMinutes % 60}분</span>
                                        </div>
                                    )}
                                    
                                    {/* 숙박 연동 버튼은 사용자 피드백에 따라 제거 (필요시 다른 방식으로 제안) */}
                                </div>
                            )}
                        </div>

                        {isAccEvent && (
                            <div className="flex items-center gap-1.5 xl:gap-3 md:gap-3">
                                <div className="flex flex-col items-center">
                                    <span className="text-[7px] font-black uppercase text-primary tracking-tighter opacity-60">실제 예정</span>
                                    <div className="flex items-center gap-1 mt-0.5">
                                        <input
                                            type="time"
                                            value={expectedTime}
                                            onChange={(e) => handleTimeChange(e.target.value)}
                                            className={cn(
                                                "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-md px-1 py-0.5 text-[10px] xl:text-[11px] font-black focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all w-[85px] xl:w-auto",
                                                isInvalid() && "border-red-500 text-red-500 focus:ring-red-500/20"
                                            )}
                                        />
                                        {event.autoGeneratedType === 'check-in' && (
                                            <div className="flex items-center gap-1">
                                                {event.possibleCheckInTime ? (
                                                    <button
                                                        onClick={() => {
                                                            const [h, m] = event.possibleCheckInTime!.split(':').map(Number);
                                                            let totalMins = h * 60 + m + 60; // 1 hr buffer
                                                            const hotelIn = event.checkInTime || '15:00';
                                                            const [hh, mm] = hotelIn.split(':').map(Number);
                                                            const hotelInMins = hh * 60 + mm;
                                                            if (totalMins < hotelInMins) totalMins = hotelInMins;
                                                            const paddedTime = `${String(Math.floor(totalMins/60)%24).padStart(2,'0')}:${String(totalMins%60).padStart(2,'0')}`;
                                                            handleTimeChange(paddedTime);
                                                        }}
                                                        className="px-2 py-0.5 xl:px-2.5 xl:py-1 bg-amber-50 hover:bg-amber-100 dark:bg-amber-900/30 dark:hover:bg-amber-900/50 rounded-lg text-primary transition-all flex items-center gap-1 border border-amber-100 dark:border-amber-800 group/magic"
                                                        title={`항공편 도착 시각(${event.possibleCheckInTime})을 고려한 추천 시각으로 설정`}
                                                    >
                                                        <span className="material-symbols-rounded text-[14px] xl:text-xs group-hover/magic:scale-110 transition-transform">bolt</span>
                                                        <span className="text-[9px] xl:text-[10px] font-black uppercase tracking-tighter">추천</span>
                                                    </button>
                                                ) : event.checkInTime ? (
                                                    <button
                                                        onClick={() => handleTimeChange(event.checkInTime!)}
                                                        className="px-2 py-0.5 xl:px-2.5 xl:py-1 bg-amber-50 hover:bg-amber-100 dark:bg-amber-900/30 dark:hover:bg-amber-900/50 rounded-lg text-amber-600 dark:text-amber-400 transition-all flex items-center gap-1 border border-amber-100 dark:border-amber-800 group/magic"
                                                        title={`공식 체크인 개시 시각(${event.checkInTime})으로 설정`}
                                                    >
                                                        <span className="material-symbols-rounded text-[14px] xl:text-xs group-hover/magic:scale-110 transition-transform">key</span>
                                                        <span className="text-[9px] xl:text-[10px] font-black uppercase tracking-tighter">추천</span>
                                                    </button>
                                                ) : null}
                                            </div>
                                        )}
                                        {isFlightConflict() && (
                                            <div className="relative group/conflict">
                                                <span className="material-symbols-rounded text-xs text-orange-500 animate-pulse cursor-help">flight_takeoff</span>
                                                <div className="absolute bottom-full right-0 mb-2 w-40 p-2 bg-orange-500 text-white text-[8px] font-black rounded-lg opacity-0 group-hover/conflict:opacity-100 transition-opacity pointer-events-none shadow-xl z-50">
                                                    비행 시각과 겹칩니다. 실제 체크인 가능 여부를 확인하세요.
                                                </div>
                                            </div>
                                        )}
                                        {isInvalid() && (
                                            <div className="relative group/warn">
                                                <span className="material-symbols-rounded text-xs text-red-500 animate-pulse cursor-help">warning</span>
                                                <div className="absolute bottom-full right-0 mb-2 w-32 p-2 bg-red-500 text-white text-[8px] font-black rounded-lg opacity-0 group-hover/warn:opacity-100 transition-opacity pointer-events-none shadow-xl z-50">
                                                    {event.autoGeneratedType === 'check-in' ? '체크인 권장 시간보다 빠릅니다.' : '체크아웃 시간을 초과했습니다.'}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>
                                <button
                                    onClick={() => onNavigateToSection?.('accommodation')}
                                    className="p-1.5 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg text-slate-400 hover:text-primary transition-all flex flex-col items-center gap-0.5"
                                    title="숙소 상세로 이동"
                                >
                                    <span className="material-symbols-rounded text-sm font-black">info</span>
                                    <span className="text-[7px] font-black uppercase">상세</span>
                                </button>
                            </div>
                        )}

                        {isReservationEvent && (
                            <div className="flex items-center gap-1.5 xl:gap-3 md:gap-3">
                                <button
                                    onClick={() => onNavigateToSection?.('reservations')}
                                    className="p-1.5 hover:bg-black/5 dark:hover:bg-white/5 rounded-lg text-slate-400 hover:text-primary transition-all flex flex-col items-center gap-0.5"
                                    title="예약 상세로 이동"
                                >
                                    <span className="material-symbols-rounded text-sm font-black">info</span>
                                    <span className="text-[7px] font-black uppercase">상세</span>
                                </button>
                            </div>
                        )}

                        {/* Actions */}
                        {!isAccEvent && (
                            <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                {!isFlightSegment && (
                                    <button
                                        onClick={() => onEdit?.(event)}
                                        className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg text-slate-400 hover:text-primary transition-colors"
                                    >
                                        <span className="material-symbols-rounded text-sm font-bold">edit</span>
                                    </button>
                                )}
                                
                                {isAuto && (event.autoGeneratedType === 'flight' || event.autoGeneratedType === 'public-transport' || event.autoGeneratedType === 'reservation') && (
                                    <button
                                        onClick={() => onNavigateToSection?.(event.autoGeneratedType === 'reservation' ? 'reservations' : 'transport')}
                                        className="p-2 hover:bg-sky-50 dark:hover:bg-sky-900/20 rounded-lg text-sky-400 hover:text-sky-500 transition-colors"
                                        title={event.autoGeneratedType === 'reservation' ? '예약 관리로 이동' : '항공/교통 관리로 이동'}
                                    >
                                        <span className="material-symbols-rounded text-sm font-bold">{event.autoGeneratedType === 'reservation' ? 'confirmation_number' : 'directions_transit'}</span>
                                    </button>
                                )}

                                <button
                                    onClick={() => onAddComment?.(event.id)}
                                    className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg text-slate-400 hover:text-primary transition-all flex items-center gap-1 shrink-0 relative"
                                    title="코멘트 남기기"
                                >
                                    <span className="material-symbols-rounded text-sm font-bold">add_comment</span>
                                    {eventComments.length > 0 && (
                                        <span className={cn(
                                            "text-[9px] font-black px-1 rounded-full min-w-[14px] h-[14px] flex items-center justify-center -ml-1",
                                            pendingCount > 0 ? "bg-red-500 text-white" : "bg-slate-200 text-slate-600"
                                        )}>
                                            {eventComments.length}
                                        </span>
                                    )}
                                </button>

                                {!(isAuto && (event.autoGeneratedType === 'flight' || event.autoGeneratedType === 'public-transport' || event.autoGeneratedType === 'reservation')) && !isFlightSegment && (
                                    <button
                                        onClick={() => onDelete?.(event.id)}
                                        className="p-2 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg text-slate-400 hover:text-red-500 transition-colors"
                                        title="삭제"
                                    >
                                        <span className="material-symbols-rounded text-sm font-bold">delete</span>
                                    </button>
                                )}
                            </div>
                        )}
                    </div>
                </div>
            </motion.div>
        </div>
    );
}
