'use client';

import { useState, useEffect } from 'react';
import { TripEvent, TransportationMethod, TRANSPORT_ICONS, timeToMinutes, minutesToTime } from '@pplaner/shared';
import { cn } from '@pplaner/shared';
import { motion, AnimatePresence } from 'framer-motion';
import { TimeInput } from '../../common/FormComponents';
import { Plane, Clock, Globe, MapPin } from 'lucide-react';

interface PendingEventCardProps {
    event: TripEvent;
    onConfirm: (time: string, extraData?: any) => void;
}

export default function PendingEventCard({ event, onConfirm }: PendingEventCardProps) {
    const [isConfirming, setIsConfirming] = useState(false);
    const isBundle = event.autoGeneratedType === 'flight-bundle';
    
    // For single events
    const [time, setTime] = useState(event.startTime || '12:00');
    const [endTime, setEndTime] = useState(event.endTime || '');
    
    // For flight bundles - use smart defaults if it's a flight bundle
    const flightDep = event.startTime || '12:00'; // departure
    const flightArr = event.endTime || '12:00';   // arrival
    const isInternational = event.isInternational;

    const getDefaultPrepTime = () => {
        const depMin = timeToMinutes(flightDep);
        const offset = isInternational ? 180 : 90; // 3h or 1.5h
        return minutesToTime(depMin - offset);
    };

    const getDefaultEntryTime = () => {
        const arrMin = timeToMinutes(flightArr);
        const offset = isInternational ? 60 : 30; // 1h or 30m
        return minutesToTime(arrMin + offset);
    };

    const [prepTime, setPrepTime] = useState(getDefaultPrepTime());
    const [entryTime, setEntryTime] = useState(getDefaultEntryTime());

    const flightDurMin = timeToMinutes(flightArr) - timeToMinutes(flightDep);
    const flightDurFormatted = `${Math.floor(flightDurMin / 60)}h ${flightDurMin % 60}m`;

    const handlePresetPrep = (hours: number) => {
        const depMin = timeToMinutes(flightDep);
        setPrepTime(minutesToTime(depMin - hours * 60));
    };

    const handlePresetEntry = (hours: number) => {
        const arrMin = timeToMinutes(flightArr);
        setEntryTime(minutesToTime(arrMin + hours * 60));
    };

    // Update defaults when bundle status or flight times change
    useEffect(() => {
        if (isBundle) {
            setPrepTime(getDefaultPrepTime());
            setEntryTime(getDefaultEntryTime());
        }
    }, [flightDep, flightArr, isInternational, isBundle]);

    const getIcon = () => {
        if (isBundle) return 'flight';
        if (event.autoGeneratedType === 'flight') {
            return event.id.endsWith('-prep') ? 'flight_takeoff' : 'flight_land';
        }
        if (event.autoGeneratedType === 'flight-segment') return 'flight';
        if (event.autoGeneratedType === 'check-in') return 'login';
        if (event.autoGeneratedType === 'check-out') return 'logout';
        if (event.autoGeneratedType === 'driving') return 'directions_car';
        if (event.autoGeneratedType === 'public-transport') return TRANSPORT_ICONS[event.subCategory as TransportationMethod] || 'directions_transit';
        return 'event';
    };

    const getLabel = () => {
        if (isBundle) return '항공편 일정 묶음';
        if (event.autoGeneratedType === 'check-in') return '체크인 예정';
        if (event.autoGeneratedType === 'check-out') return '체크아웃 예정';
        if (event.autoGeneratedType === 'flight') {
            return event.id.endsWith('-prep') ? '항공편 출발 수속' : '항공편 도착 및 수속';
        }
        if (event.autoGeneratedType === 'driving') return event.title;
        return event.title;
    };

    const handleConfirm = () => {
        if (isBundle) {
            onConfirm(prepTime, { entryTime });
        } else {
            onConfirm(time);
        }
    };

    return (
        <div className={cn(
            "bg-slate-50/50 dark:bg-slate-800/30 border border-slate-200/50 dark:border-slate-800/50 rounded-2xl p-3 flex flex-col gap-2 transition-all hover:bg-white dark:hover:bg-slate-800",
            isConfirming && "ring-2 ring-primary/20 border-primary/30"
        )}>
            <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-3 min-w-0">
                    <div className="w-8 h-8 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center shrink-0">
                        <span className="material-symbols-rounded text-lg text-slate-400">
                            {getIcon()}
                        </span>
                    </div>
                    <div className="flex flex-col min-w-0">
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-wider">{getLabel()}</span>
                        <div className="flex items-center gap-2">
                            <span className="text-xs font-bold text-slate-700 dark:text-slate-200 truncate">{event.title}</span>
                            {!isBundle && event.startTime && (
                                <span className="text-[10px] font-bold text-primary/60 bg-primary/5 px-1.5 py-0.5 rounded-md border border-primary/10">
                                    {event.startTime} 예약
                                </span>
                            )}
                        </div>
                    </div>
                </div>

                {!isConfirming ? (
                    <button 
                        onClick={() => setIsConfirming(true)}
                        className="px-3 py-1.5 bg-primary/10 hover:bg-primary text-primary hover:text-white rounded-lg text-[10px] font-black transition-all whitespace-nowrap"
                    >
                        일정 확정하기
                    </button>
                ) : (
                    <div className="flex items-center gap-2 animate-in fade-in slide-in-from-right-2">
                        <button 
                            onClick={() => setIsConfirming(false)}
                            className="p-1.5 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
                        >
                            <span className="material-symbols-rounded text-lg">close</span>
                        </button>
                    </div>
                )}
            </div>

            <AnimatePresence>
                {isConfirming && (
                    <motion.div 
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden"
                    >
                        <div className="pt-2.5 border-t border-slate-200/50 dark:border-slate-800/50 flex flex-col gap-3">
                            {isBundle && (
                                <div className="bg-slate-100/50 dark:bg-slate-950/20 rounded-xl p-2.5 space-y-1.5 border border-slate-200/50 dark:border-slate-800/30">
                                    <div className="flex items-center justify-between">
                                        <div className="flex items-center gap-1.5">
                                            <Plane className="w-2.5 h-2.5 text-primary/70" />
                                            <span className="text-[9px] font-black text-slate-500 uppercase tracking-widest">Flight Context</span>
                                        </div>
                                        <div className="flex items-center gap-1 px-1.5 py-0.5 bg-white/50 dark:bg-slate-800/50 rounded-md border border-slate-200 dark:border-slate-700">
                                            <Globe className="w-2.5 h-2.5 text-primary/60" />
                                            <span className="text-[8px] font-black text-slate-500">
                                                {isInternational ? 'International' : 'Domestic'}
                                            </span>
                                        </div>
                                    </div>
                                    <div className="flex items-center justify-between">
                                        <div className="flex items-center gap-3">
                                            <div className="flex flex-col">
                                                <span className="text-[8px] font-bold text-slate-400 leading-none mb-0.5">DEP</span>
                                                <span className="text-[11px] font-black text-slate-700 dark:text-slate-200">{flightDep}</span>
                                            </div>
                                            <div className="flex flex-col items-center gap-0.5 px-2">
                                                <div className="w-8 h-[1px] bg-slate-300 dark:bg-slate-700 relative">
                                                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-1 h-1 bg-primary/40 rounded-full" />
                                                </div>
                                                <span className="text-[8px] font-black text-primary/60 whitespace-nowrap">{flightDurFormatted}</span>
                                            </div>
                                            <div className="flex flex-col text-right">
                                                <span className="text-[8px] font-bold text-slate-400 leading-none mb-0.5">ARR</span>
                                                <span className="text-[11px] font-black text-slate-700 dark:text-slate-200">{flightArr}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}

                            {isBundle ? (
                                <div className="flex flex-col gap-4">
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="space-y-2">
                                            <div className="flex flex-col gap-1">
                                                <div className="flex items-center justify-between px-1">
                                                    <label className="text-[9px] font-black text-slate-400 uppercase">출발공항 도착</label>
                                                    <div className="flex items-center gap-1">
                                                        {(isInternational ? [4, 3, 2] : [2, 1.5, 1]).map(h => (
                                                            <button 
                                                                key={h}
                                                                onClick={() => handlePresetPrep(h)}
                                                                className="px-1 py-0.5 bg-slate-100 dark:bg-slate-800 hover:bg-primary/10 text-slate-500 hover:text-primary rounded text-[8px] font-black transition-colors"
                                                            >
                                                                {h}h
                                                            </button>
                                                        ))}
                                                    </div>
                                                </div>
                                                <TimeInput 
                                                    value={prepTime}
                                                    onChange={setPrepTime}
                                                    className="!space-y-0"
                                                />
                                            </div>
                                            <div className="flex items-center gap-1 px-1 opacity-80">
                                                <Clock className="w-2.5 h-2.5 text-primary/50" />
                                                <span className="text-[9px] font-bold text-slate-500">
                                                    체류: {Math.floor((timeToMinutes(flightDep) - timeToMinutes(prepTime)) / 60)}h {(timeToMinutes(flightDep) - timeToMinutes(prepTime)) % 60}m
                                                </span>
                                            </div>
                                        </div>

                                        <div className="space-y-2">
                                            <div className="flex flex-col gap-1">
                                                <div className="flex items-center justify-between px-1">
                                                    <label className="text-[9px] font-black text-slate-400 uppercase">도착공항 수속</label>
                                                    <div className="flex items-center gap-1">
                                                        {(isInternational ? [2, 1.5, 1] : [1, 0.5]).map(h => (
                                                            <button 
                                                                key={h}
                                                                onClick={() => handlePresetEntry(h)}
                                                                className="px-1 py-0.5 bg-slate-100 dark:bg-slate-800 hover:bg-primary/10 text-slate-500 hover:text-primary rounded text-[8px] font-black transition-colors"
                                                            >
                                                                {h === 0.5 ? '30m' : `${h}h`}
                                                            </button>
                                                        ))}
                                                    </div>
                                                </div>
                                                <TimeInput 
                                                    value={entryTime}
                                                    onChange={setEntryTime}
                                                    className="!space-y-0"
                                                />
                                            </div>
                                            <div className="flex items-center gap-1 px-1 opacity-80">
                                                <Clock className="w-2.5 h-2.5 text-primary/50" />
                                                <span className="text-[9px] font-bold text-slate-500">
                                                    소요: {Math.floor((timeToMinutes(entryTime) - timeToMinutes(flightArr)) / 60)}h {(timeToMinutes(entryTime) - timeToMinutes(flightArr)) % 60}m
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ) : (
                                <div className="space-y-3">
                                    <div className="grid grid-cols-2 gap-3">
                                        <TimeInput 
                                            label="시작 시간"
                                            value={time}
                                            onChange={setTime}
                                            rangeStart={event.rangeStart}
                                            rangeEnd={event.rangeEnd}
                                        />
                                        <TimeInput 
                                            label="종료 시간"
                                            value={endTime}
                                            onChange={setEndTime}
                                            rangeStart={event.rangeStart}
                                            rangeEnd={event.rangeEnd}
                                        />
                                    </div>
                                    {event.rangeStart && event.rangeEnd && (
                                        <div className="flex items-center gap-1.5 px-2 py-1.5 bg-amber-50 dark:bg-amber-900/10 rounded-xl border border-amber-200/30 dark:border-amber-800/30">
                                            <span className="material-symbols-rounded text-[14px] text-amber-500">info</span>
                                            <p className="text-[9px] font-black text-amber-600 dark:text-amber-400">
                                                {event.autoGeneratedType === 'check-in' ? '체크인 가능' : '체크아웃 시간'}: {event.rangeStart} ~ {event.rangeEnd}
                                            </p>
                                        </div>
                                    )}
                                </div>
                            )}
                            
                            <button 
                                onClick={handleConfirm}
                                className="w-full py-3 bg-primary text-white rounded-2xl text-[11px] font-black shadow-xl shadow-primary/20 hover:scale-[1.02] active:scale-[0.98] transition-all"
                            >
                                일정 확정 및 타임라인 반영
                            </button>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

