'use client';

import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { cn } from '@pplaner/shared';
import { TripEvent } from '@pplaner/shared';
import TimelineEventCard from '../TimelineEventCard';

interface SortableEventCardProps {
    event: TripEvent;
    dayIdx: number;
    onEdit: (event: Partial<TripEvent>) => void;
    onRemove: (id: string) => void;
    onAddComment?: (eventId: string) => void;
    onNavigateToSection?: (section: string) => void;
    isHighlighted?: boolean;
}

export default function SortableEventCard({ 
    event, 
    dayIdx, 
    onEdit, 
    onRemove, 
    onAddComment,
    onNavigateToSection,
    isHighlighted 
}: SortableEventCardProps) {
    const {
        attributes,
        listeners,
        setNodeRef,
        transform,
        transition,
        isDragging
    } = useSortable({
        id: event.id,
        disabled: event.autoGeneratedType === 'flight-segment' // Only the main flight duration bar is strictly non-draggable
    });

    const style = {
        transform: CSS.Translate.toString(transform),
        transition,
        opacity: isDragging ? 0.3 : 1,
        zIndex: isDragging ? 50 : 1,
    };

    return (
        <div 
            ref={setNodeRef} 
            style={style} 
            className={cn("relative", isDragging && "z-50")}
        >
            <TimelineEventCard 
                event={event} 
                onEdit={onEdit}
                onDelete={onRemove}
                onAddComment={onAddComment}
                onNavigateToSection={onNavigateToSection}
                isHighlighted={isHighlighted}
                dragHandleProps={{...attributes, ...listeners}}
                isDragging={isDragging}
            />
        </div>
    );
}
