'use client';

import { useMemo } from 'react';
import { useTripStore } from '@pplaner/shared';
import { TripEvent, DailyPlan, TransportationMethod } from '@pplaner/shared';
import { Airport, AIRPORTS } from '@pplaner/shared';
import { MainCategory, SubCategory, CATEGORY_MAP } from '@pplaner/shared';
import { parseISO, format, addDays, isValid } from 'date-fns';
import { ko } from 'date-fns/locale';
import { timeToMinutes, minutesToTime } from '@pplaner/shared';
import { MapProps } from '@/components/common/MapComponent';

const safeFormat = (dateStr: string | undefined, formatStr: string, options?: any) => {
    if (!dateStr) return '';
    try {
        const d = parseISO(dateStr);
        if (!isValid(d)) return '';
        return format(d, formatStr, options);
    } catch (e) {
        return '';
    }
};

const safeAddDaysFormat = (dateStr: string | undefined, days: number, formatStr: string) => {
    if (!dateStr) return '';
    try {
        const d = parseISO(dateStr);
        if (!isValid(d)) return '';
        return format(addDays(d, days), formatStr);
    } catch (e) {
        return '';
    }
};

export interface EnhancedTimelineDay extends DailyPlan {
    dayOfWeek: string;
    visitSummary: string;
    flexibleEvents: TripEvent[];
    scheduledEvents: TripEvent[];
    pendingEvents: TripEvent[];
    daySummary?: {
        flights: TripEvent[];
        accommodations: TripEvent[];
        weather?: {
            temp: number;
            condition: string;
            icon: string;
        };
    };
}

export function useTimelineData(showOnlyBooked: boolean, highlightedEventId?: string | null) {
    const trip = useTripStore((state) => state.currentTrip);

    const timelineWithReservations = useMemo(() => {
        if (!trip) return [];

        return (trip.dailyTimeline || []).map((plan: DailyPlan, dayIdx: number) => {
            const dateStr = plan.date;
            const resEvents: TripEvent[] = [];

            // 1. Add Flights
            (trip.flights || []).forEach(f => {
                const isBooked = f.isBooked ?? false;
                if (!f.departureTime || !f.arrivalTime || !f.date || (showOnlyBooked && !isBooked)) return;
                
                const depAirport = AIRPORTS.find((a: Airport) => a.code === f.departureLocation);
                const arrAirport = AIRPORTS.find((a: Airport) => a.code === f.arrivalLocation);
                const depAirportName = depAirport ? `${depAirport.nameKo} (${depAirport.code})` : f.departureLocation || '출발 공항';
                const arrAirportName = arrAirport ? `${arrAirport.nameKo} (${arrAirport.code})` : f.arrivalLocation || '도착 공항';
                const flightCode = f.airline ? (f.flightNumber?.startsWith(f.airline) ? f.flightNumber : `${f.airline}${f.flightNumber || ''}`) : (f.flightNumber || '항공편');

                if (f.date === dateStr) {
                    const prepDuration = f.prepDurationMinutes ?? (f.isInternational !== false ? 120 : 60);
                    const depMinutes = timeToMinutes(f.departureTime);
                    const prepStartTime = minutesToTime(depMinutes - prepDuration);
                    
                    resEvents.push({
                        id: `flight-${f.id}-prep`,
                        title: `${flightCode} 출발 수속`,
                        type: 'transport',
                        mainCategory: 'transport',
                        subCategory: 'flight',
                        isAutoGenerated: true,
                        autoGeneratedType: 'flight',
                        isFixedTime: true,
                        startTime: prepStartTime,
                        endTime: f.departureTime,
                        location: { 
                            name: depAirportName,
                            lat: f.departureLat,
                            lng: f.departureLng
                        },
                        category: '항공',
                        sourceId: f.id,
                        prepDurationMinutes: prepDuration,
                        durationMinutes: prepDuration,
                        isInternational: f.isInternational,
                        isBooked
                    });

                    const durationText = f.flightDurationMinutes 
                        ? (f.flightDurationMinutes >= 60 
                            ? `${Math.floor(f.flightDurationMinutes / 60)}시간 ${f.flightDurationMinutes % 60}분` 
                            : `${f.flightDurationMinutes}분`)
                        : '비행';
                    
                    resEvents.push({
                        id: `flight-${f.id}-dur`,
                        title: `${flightCode} 운항`,
                        type: 'transport',
                        mainCategory: 'transport',
                        subCategory: 'flight',
                        isAutoGenerated: true,
                        autoGeneratedType: 'flight-segment',
                        isFixedTime: true,
                        startTime: f.departureTime,
                        endTime: f.arrivalTime,
                        location: { 
                            name: `${depAirportName} → ${arrAirportName}`,
                        },
                        category: '항공',
                        sourceId: f.id,
                        memo: `${flightCode} (${durationText} 소요)`,
                        isBooked,
                        isInternational: f.isInternational
                    });
                }

                let arrivalDayDate = f.date;
                if (f.date && f.departureTime && f.arrivalTime) {
                    const depMin = timeToMinutes(f.departureTime);
                    const arrMin = timeToMinutes(f.arrivalTime);
                    if (arrMin < depMin) {
                        arrivalDayDate = safeAddDaysFormat(f.date, 1, 'yyyy-MM-dd');
                    }
                }

                if (arrivalDayDate === dateStr) {
                    const entryDuration = f.entryDurationMinutes ?? (f.isInternational !== false ? 60 : 30);
                    const arrMinutes = timeToMinutes(f.arrivalTime);
                    const entryEndTime = minutesToTime(arrMinutes + entryDuration);
                    
                    resEvents.push({
                        id: `flight-${f.id}-arr`,
                        title: `${flightCode} 도착 및 수속`,
                        type: 'transport',
                        mainCategory: 'transport',
                        subCategory: 'flight',
                        isAutoGenerated: true,
                        autoGeneratedType: 'flight',
                        isFixedTime: true,
                        startTime: f.arrivalTime,
                        endTime: entryEndTime,
                        location: { 
                            name: arrAirportName,
                            lat: f.arrivalLat,
                            lng: f.arrivalLng
                        },
                        category: '항공',
                        sourceId: f.id,
                        entryDurationMinutes: entryDuration,
                        durationMinutes: entryDuration,
                        isInternational: f.isInternational,
                        isBooked
                    });
                }
            });

            // 2. Add Driving
            (trip.driving || []).forEach(d => {
                const isBooked = d.isBooked ?? false;
                if (!d.pickupTime || !d.date || (showOnlyBooked && !isBooked)) return;

                if (d.date === dateStr) {
                    resEvents.push({
                        id: `driving-${d.id}-pickup`,
                        title: `${d.isRental ? '렌터카 픽업' : '직접 운전 시작'}`,
                        type: 'transport',
                        mainCategory: 'transport',
                        subCategory: 'taxi', // Using taxi as subcategory for driving representation
                        isAutoGenerated: true,
                        autoGeneratedType: 'driving',
                        isFixedTime: true,
                        startTime: d.pickupTime.includes('T') ? d.pickupTime.split('T')[1] : d.pickupTime,
                        location: { 
                            name: d.pickupLocation || '픽업 위치',
                            lat: d.pickupLat,
                            lng: d.pickupLng
                        },
                        category: '교통',
                        sourceId: d.id,
                        isBooked,
                        isPointInTime: true
                    });
                }

                if (d.returnTime && d.date === dateStr) {
                     resEvents.push({
                        id: `driving-${d.id}-return`,
                        title: `${d.isRental ? '렌터카 반납' : '운전 종료'}`,
                        type: 'transport',
                        mainCategory: 'transport',
                        subCategory: 'taxi',
                        isAutoGenerated: true,
                        autoGeneratedType: 'driving',
                        isFixedTime: true,
                        startTime: d.returnTime.includes('T') ? d.returnTime.split('T')[1] : d.returnTime,
                        location: { 
                            name: d.returnLocation || '반납 위치',
                            lat: d.returnLat,
                            lng: d.returnLng
                        },
                        category: '교통',
                        sourceId: d.id,
                        isBooked,
                        isPointInTime: true
                    });
                }
            });

            // 3. Add Public Transport
            (trip.publicTransport || []).forEach(p => {
                const isBooked = p.isBooked ?? false;
                if (!p.departureTime || p.isTimeUndecided || p.isDateUndecided || p.date !== dateStr || (showOnlyBooked && !isBooked)) return;
                
                const methodMap: Record<string, TransportationMethod> = {
                    bus: 'bus', train: 'train', ferry: 'ship', taxi: 'taxi', ropeway: 'bus', trolleybus: 'bus', pass: 'train'
                };
                const method = methodMap[p.type] || 'bus';

                resEvents.push({
                    id: `public-${p.id}`,
                    title: `${p.name || '대중교통'} 이용`,
                    type: 'transport',
                    mainCategory: 'transport',
                    subCategory: method as SubCategory,
                    isAutoGenerated: true,
                    autoGeneratedType: 'public-transport',
                    isFixedTime: true,
                    startTime: p.departureTime,
                    endTime: p.arrivalTime || minutesToTime(timeToMinutes(p.departureTime) + (p.duration || 60)),
                    location: { 
                        name: p.departureLocation || '출발지',
                        lat: p.departureLat,
                        lng: p.departureLng
                    },
                    category: '교통',
                    sourceId: p.id,
                    isBooked
                });
            });

            // 4. Add Accommodations
            (trip.accommodation || []).forEach(acc => {
                const isBooked = acc.status === 'booked';
                if (showOnlyBooked && !isBooked) return;

                const isStart = dateStr === acc.startDate;
                const isEnd = dateStr === acc.endDate;
                const isMiddle = dateStr > acc.startDate && (acc.endDate ? dateStr < acc.endDate : true);

                if (isStart) {
                    const arrivalFlight = trip.flights.find(f => {
                        let flightArrivalDate = f.date;
                        if (f.date && f.departureTime && f.arrivalTime) {
                            const depM = timeToMinutes(f.departureTime);
                            const arrM = timeToMinutes(f.arrivalTime);
                            if (arrM < depM) {
                                flightArrivalDate = safeAddDaysFormat(f.date, 1, 'yyyy-MM-dd');
                            }
                        }
                        return flightArrivalDate === dateStr;
                    });
                    
                    const possibleCheckInTime = arrivalFlight 
                        ? minutesToTime(timeToMinutes(arrivalFlight.arrivalTime) + (arrivalFlight.entryDurationMinutes ?? (arrivalFlight.isInternational !== false ? 60 : 30)))
                        : undefined;

                    const requestedCheckInTime = acc.expectedCheckInTime || acc.checkInStartTime || '15:00';
                    let finalCheckInTime = requestedCheckInTime;
                    let isTimeAdjusted = false;

                    if (possibleCheckInTime) {
                        const requestedMin = timeToMinutes(requestedCheckInTime);
                        const possibleMin = timeToMinutes(possibleCheckInTime);
                        if (possibleMin > requestedMin) {
                            finalCheckInTime = possibleCheckInTime;
                            isTimeAdjusted = true;
                        }
                    }

                    resEvents.push({
                        id: `acc-${acc.id}-in`,
                        title: `${acc.name} 체크인`,
                        type: 'accommodation',
                        mainCategory: 'accommodation',
                        subCategory: acc.type as SubCategory,
                        isAutoGenerated: true,
                        autoGeneratedType: 'check-in',
                        isFixedTime: true,
                        startTime: finalCheckInTime,
                        rangeStart: acc.checkInStartTime?.split('-')[0]?.trim() || '15:00',
                        rangeEnd: acc.checkInStartTime?.split('-')[1]?.trim() || '23:59',
                        location: { 
                            name: acc.name, 
                            address: acc.location,
                            lat: acc.lat,
                            lng: acc.lng
                        },
                        category: '숙소',
                        sourceId: acc.id,
                        checkInTime: acc.checkInStartTime,
                        expectedCheckInTime: acc.expectedCheckInTime,
                        possibleCheckInTime,
                        isTimeAdjusted,
                        isPointInTime: true,
                        isBooked,
                        memo: isTimeAdjusted ? `항공편 도착 및 수속 시간을 고려하여 체크인 시간을 ${finalCheckInTime}으로 자동 조정했습니다.` : undefined
                    } as TripEvent);
                } 
                
                if (isEnd) {
                    resEvents.push({
                        id: `acc-${acc.id}-out`,
                        title: `${acc.name} 체크아웃`,
                        type: 'accommodation',
                        mainCategory: 'accommodation',
                        subCategory: acc.type as SubCategory,
                        isAutoGenerated: true,
                        autoGeneratedType: 'check-out',
                        isFixedTime: true,
                        startTime: acc.expectedCheckOutTime || acc.checkOutEndTime || '11:00',
                        rangeStart: '05:00',
                        rangeEnd: acc.checkOutEndTime?.split('-')[1]?.trim() || acc.checkOutEndTime || '11:00',
                        location: { 
                            name: acc.name, 
                            address: acc.location,
                            lat: acc.lat,
                            lng: acc.lng
                        },
                        category: '숙소',
                        sourceId: acc.id,
                        checkOutTime: acc.checkOutEndTime,
                        expectedCheckOutTime: acc.expectedCheckOutTime,
                        isPointInTime: true,
                        isBooked
                    } as TripEvent);
                }

                if (isMiddle) {
                    resEvents.push({
                        id: `acc-${acc.id}-stay-${dateStr}`,
                        title: `숙박 중: ${acc.name}`,
                        type: 'accommodation',
                        mainCategory: 'accommodation',
                        subCategory: acc.type as SubCategory,
                        isAutoGenerated: true,
                        autoGeneratedType: 'stay',
                        isFixedTime: false,
                        location: { 
                            name: acc.name, 
                            address: acc.location,
                            lat: acc.lat,
                            lng: acc.lng
                        },
                        category: '숙소',
                        sourceId: acc.id,
                        isBooked
                    } as TripEvent);
                }
            });

            // 5. Add General Reservations
            (trip.reservations || []).forEach(res => {
                if (!res.date || res.date !== dateStr || (showOnlyBooked && res.status !== 'confirmed')) return;

                resEvents.push({
                    id: `res-${res.id}`,
                    title: res.title,
                    type: 'reservation',
                    mainCategory: 'reservation',
                    subCategory: 'activity', 
                    isAutoGenerated: true,
                    autoGeneratedType: 'reservation',
                    isFixedTime: !!res.time,
                    startTime: res.time,
                    location: { 
                        name: res.location || '예약 장소',
                        lat: res.lat,
                        lng: res.lng
                    },
                    category: '예약',
                    sourceId: res.id,
                    isBooked: res.status === 'confirmed',
                    cost: res.cost,
                    currency: res.currency,
                    links: res.link ? [res.link] : []
                } as TripEvent);
            });

            // Filter resEvents: 
            // 1. "stay" events remain automatic.
            // 2. Others move to pending unless they exist in plan.events (confirmed).
            const resIds = new Set(resEvents.map(e => e.id));
            const confirmedAutoEvents = plan.events.filter(e => e.isAutoGenerated && resIds.has(e.id));
            
            const allPendingIndividual = resEvents.filter(e => 
                e.autoGeneratedType !== 'stay' && 
                !plan.events.some(pe => pe.id === e.id)
            );

            const flightPending = allPendingIndividual.filter(e => e.autoGeneratedType === 'flight' || e.autoGeneratedType === 'flight-segment');
            const otherPending = allPendingIndividual.filter(e => e.autoGeneratedType !== 'flight' && e.autoGeneratedType !== 'flight-segment');

            // Group flights by sourceId
            const flightBundles: TripEvent[] = [];
            const processedFlightSourceIds = new Set<string>();

            flightPending.forEach(e => {
                if (e.sourceId && !processedFlightSourceIds.has(e.sourceId)) {
                    processedFlightSourceIds.add(e.sourceId);
                    // Find all parts for this flight on this day
                    const parts = resEvents.filter(p => p.sourceId === e.sourceId);
                    const flightSegment = parts.find(p => p.autoGeneratedType === 'flight-segment');
                    const isInternational = parts.some(p => p.isInternational);
                    
                    // Only bundle if NOT already confirmed
                    const isAnyConfirmed = parts.some(p => plan.events.some(pe => pe.id === p.id));
                    if (!isAnyConfirmed) {
                        flightBundles.push({
                            id: `flight-bundle-${e.sourceId}`,
                            title: e.title.split(' ')[0] + ' 항공편 전체', // e.g. "KE123 항공편 전체"
                            type: 'transport',
                            isAutoGenerated: true,
                            autoGeneratedType: 'flight-bundle',
                            sourceId: e.sourceId,
                            startTime: flightSegment?.startTime, // Raw departure time
                            endTime: flightSegment?.endTime, // Raw arrival time
                            isInternational,
                            // Store components for confirmation logic
                            memo: JSON.stringify(parts) 
                        } as TripEvent);
                    }
                }
            });

            const pendingEvents = [...otherPending, ...flightBundles];

            const filteredUserEvents = plan.events.filter(e => !e.isAutoGenerated);
            let allEvents = [
                ...filteredUserEvents, 
                ...confirmedAutoEvents, 
                ...resEvents.filter(e => e.autoGeneratedType === 'stay')
            ];
            
            const flightsOnDay = allEvents.filter(e => e.autoGeneratedType === 'flight' || e.autoGeneratedType === 'flight-segment');
            const arrivalFlight = flightsOnDay.find(e => e.id.endsWith('-arr'));
            const departureFlight = flightsOnDay.find(e => e.id.endsWith('-prep')); // Changed from -dep to -prep to match generated IDs

            allEvents = allEvents.map(ev => {
                let currentStart = ev.startTime;
                let isTimeAdjusted = ev.isTimeAdjusted || false;
                let memo = ev.memo;

                if (!currentStart) return ev;

                const currentMin = timeToMinutes(currentStart);

                if (!ev.isAutoGenerated && departureFlight && arrivalFlight) {
                    const depMin = timeToMinutes(departureFlight.startTime!);
                    const arrMin = timeToMinutes(arrivalFlight.endTime!);
                    if (currentMin >= depMin && currentMin <= arrMin) {
                        currentStart = minutesToTime(arrMin + 15);
                        isTimeAdjusted = true;
                        memo = `비행 시간(${departureFlight.startTime} ~ ${arrivalFlight.endTime})을 피해서 일정을 ${currentStart}으로 조정했습니다.`;
                    }
                }

                if (ev.autoGeneratedType === 'check-out' && departureFlight) {
                    const depMin = timeToMinutes(departureFlight.startTime!);
                    const limitMin = depMin - 150; 
                    if (currentMin > limitMin) {
                        currentStart = minutesToTime(limitMin);
                        isTimeAdjusted = true;
                        memo = `공항 이동 및 수속 시간(출발 2.5시간 전)을 고려하여 체크아웃 시간을 ${currentStart}으로 조정했습니다.`;
                    }
                }

                return { ...ev, startTime: currentStart, isTimeAdjusted, memo };
            });

            const sortedEvents = allEvents.sort((a, b) => {
                const timeA = a.startTime || (a.isFixedTime ? '00:00' : '23:59');
                const timeB = b.startTime || (b.isFixedTime ? '00:00' : '23:59');
                if (timeA !== timeB) return timeA.localeCompare(timeB);

                const getPriority = (ev: Partial<TripEvent>) => {
                    if (ev.autoGeneratedType === 'check-out') return -2;
                    if (ev.id?.endsWith('-dep')) return -1;
                    if (ev.id?.endsWith('-arr')) return 1;
                    if (ev.autoGeneratedType === 'check-in') return 2;
                    return 0;
                };
                return getPriority(a) - getPriority(b);
            });

            const finalEvents = sortedEvents as TripEvent[];
            
            finalEvents.forEach((ev, i) => {
                if (ev.autoGeneratedType === 'check-in') {
                    const lastFlightArrival = [...finalEvents.slice(0, i)].reverse().find(e => 
                        e.autoGeneratedType === 'flight' && e.id.endsWith('-arr')
                    );
                    if (lastFlightArrival) {
                        ev.possibleCheckInTime = lastFlightArrival.endTime;
                    }
                }
            });

            const scheduledEvents = finalEvents.filter(e => e.startTime && !e.isFlexible);
            const flexibleEvents = finalEvents.filter(e => !e.startTime || e.isFlexible);

            const significantEvents = finalEvents.filter(e => !e.isAutoGenerated && e.title);
            const visitSummary = significantEvents.length > 0
                ? (significantEvents.length > 3
                    ? `${significantEvents.slice(0, 2).map(e => e.title).join(', ')} 외 ${significantEvents.length - 2}곳`
                    : significantEvents.map(e => e.title).join(', '))
                : '';

            const dailyFlights = resEvents.filter(e => e.subCategory === 'flight');
            const dailyAccommodations = resEvents.filter(e => e.mainCategory === 'accommodation' && (e.autoGeneratedType === 'check-in' || e.autoGeneratedType === 'check-out'));

            // Mock weather for now (real weather would come from an API integrated with trip location)
            const weather = {
                temp: 22 + (dayIdx % 5),
                condition: dayIdx % 3 === 0 ? '맑음' : dayIdx % 3 === 1 ? '구름' : '비',
                icon: dayIdx % 3 === 0 ? 'wb_sunny' : dayIdx % 3 === 1 ? 'cloud' : 'rainy'
            };

            return { 
                ...plan, 
                events: finalEvents,
                scheduledEvents,
                flexibleEvents,
                pendingEvents,
                dayOfWeek: safeFormat(plan.date, 'EEEE', { locale: ko }),
                visitSummary,
                daySummary: {
                    flights: dailyFlights,
                    accommodations: dailyAccommodations,
                    weather
                }
            } as EnhancedTimelineDay;
        });
    }, [trip, showOnlyBooked]);


    const mapData = useMemo(() => {
        const markers: NonNullable<MapProps['markers']> = [];
        const fullPath: { lat: number; lng: number }[] = [];
        const flightPaths: NonNullable<MapProps['flightPaths']> = [];

        if (!trip) return { markers, path: fullPath, flightPaths, initialCenter: { lat: 35.681236, lng: 139.767125 } };

        trip?.flights.forEach((f, idx) => {
            const depAir = AIRPORTS.find((a: Airport) => a.code === f.departureLocation);
            const arrAir = AIRPORTS.find((a: Airport) => a.code === f.arrivalLocation);
            
            const depLat = f.departureLat || depAir?.lat;
            const depLng = f.departureLng || depAir?.lng;
            const arrLat = f.arrivalLat || arrAir?.lat;
            const arrLng = f.arrivalLng || arrAir?.lng;

            if (depLat && depLng && arrLat && arrLng) {
                flightPaths.push({
                    from: { lat: depLat, lng: depLng },
                    to: { lat: arrLat, lng: arrLng }
                });

                if (!markers.some(m => m.id === `air-dep-${idx}-${f.departureLocation}`)) {
                    markers.push({
                        id: `air-dep-${idx}-${f.departureLocation}`,
                        lat: depLat,
                        lng: depLng,
                        title: depAir ? `${depAir.nameKo} (${depAir.code})` : f.departureLocation || '출발 공항',
                        type: 'airport',
                        category: 'transport'
                    });
                }
                if (!markers.some(m => m.id === `air-arr-${idx}-${f.arrivalLocation}`)) {
                    markers.push({
                        id: `air-arr-${idx}-${f.arrivalLocation}`,
                        lat: arrLat,
                        lng: arrLng,
                        title: arrAir ? `${arrAir.nameKo} (${arrAir.code})` : f.arrivalLocation || '도착 공항',
                        type: 'airport',
                        category: 'transport'
                    });
                }
            }
        });

        // Add wishlist items as marker candidates 
        trip?.bucketList?.forEach((item) => {
            if (item.place?.lat && item.place?.lng) {
                markers.push({
                    id: `wishlist-${item.id}`,
                    lat: item.place.lat,
                    lng: item.place.lng,
                    title: item.title,
                    type: item.mainCategory === 'meal' ? 'restaurant' : 'attraction',
                    category: item.mainCategory || 'wishlist',
                    isWishlist: true,
                    description: item.description
                });
            }
        });

        const mapSegments: Array<{ path: { lat: number; lng: number }[]; isInteractive: boolean; insertAfterIndex: number; dayIdx: number }> = [];

        timelineWithReservations.forEach((day, dayIdx) => {
            // Sort day events by time just in case to ensure path order is correct
            const dayPathEvents = day.events
                .filter(event => event.startTime && event.location?.lat && event.location?.lng)
                .sort((a, b) => (a.startTime || '00:00').localeCompare(b.startTime || '00:00'));

            let previousPos: { lat: number; lng: number } | null = null;

            dayPathEvents.forEach((event, index) => {
                const pos = { lat: event.location!.lat!, lng: event.location!.lng! };
                
                // Add to markers if it's not a stay/flight which are handled separately
                if (event.autoGeneratedType !== 'stay' && event.autoGeneratedType !== 'flight' && event.autoGeneratedType !== 'flight-segment') {
                    markers.push({
                        id: event.id,
                        lat: pos.lat,
                        lng: pos.lng,
                        title: event.title,
                        type: event.type === 'meal' ? 'restaurant' : 'attraction',
                        category: event.type,
                        day: dayIdx + 1,
                        highlighted: highlightedEventId === event.id
                    });
                }
                
                // Add to path for connection
                fullPath.push(pos);

                // Build segments for map planning mode
                if (previousPos) {
                    mapSegments.push({
                        path: [previousPos, pos],
                        isInteractive: true,
                        insertAfterIndex: index - 1, // index of the event before this line
                        dayIdx: dayIdx
                    });
                }
                previousPos = pos;
            });

            // Handle accommodations (stays and check-ins/outs)
            day.events.forEach(event => {
                if (event.location?.lat && event.location?.lng) {
                    const pos = { lat: event.location.lat, lng: event.location.lng };
                    
                    if (event.autoGeneratedType === 'stay') {
                         markers.push({
                            id: event.id,
                            lat: pos.lat,
                            lng: pos.lng,
                            title: event.title,
                            type: 'accommodation',
                            category: 'accommodation',
                            description: `${dayIdx + 1}일차 숙박 장소`,
                            day: dayIdx + 1,
                            highlighted: highlightedEventId === event.id
                        });
                    } else if (event.autoGeneratedType === 'check-in' || event.autoGeneratedType === 'check-out') {
                        // Check-in and check-out are already added in the main loop above (lines 563-586)
                        // but let's ensure they have the right type for icons
                        const existingIdx = markers.findIndex(m => m.id === event.id);
                        if (existingIdx !== -1) {
                            markers[existingIdx].type = 'accommodation';
                        }
                    }
                }
            });
        });

        return { 
            markers, 
            path: fullPath, 
            mapSegments,
            flightPaths, 
            initialCenter: fullPath[0] || markers[0] || { lat: 35.681236, lng: 139.767125 } 
        };
    }, [trip, timelineWithReservations, highlightedEventId]);

    return { 
        trip,
        timelineWithReservations,
        mapData
    };
}
