import { DragEndEvent, DragStartEvent } from '@dnd-kit/core';
import { arrayMove } from '@dnd-kit/sortable';
import { useTripStore } from '@pplaner/shared';
import { DailyPlan, TripEvent } from '@pplaner/shared';
import { timeToMinutes, minutesToTime } from '@pplaner/shared';

interface UseTimelineDndProps {
    dailyTimeline: DailyPlan[];
    setActiveId: (id: string | null) => void;
}

export function useTimelineDnd({ dailyTimeline, setActiveId }: UseTimelineDndProps) {
    const { reorderEvents, moveEvent, updateEvent, updateAccommodation } = useTripStore();

    const handleDragStart = (event: DragStartEvent) => {
        setActiveId(event.active.id as string);
    };

    const handleDragEnd = (event: DragEndEvent) => {
        const { active, over } = event;
        setActiveId(null);
        if (!over) return;

        const activeId = active.id as string;
        const overId = over.id as string;

        // Find source and destination days
        let sourceDayIdx = -1;
        let destDayIdx = -1;

        dailyTimeline.forEach((day, idx) => {
            if (day.events.find(e => e.id === activeId)) sourceDayIdx = idx;
            if (day.events.find(e => e.id === overId) || `day-${idx}` === overId) destDayIdx = idx;
        });

        if (sourceDayIdx === -1 || destDayIdx === -1) return;

        const isUserEvent = !activeId.startsWith('flight-') && !activeId.startsWith('acc-') && !activeId.startsWith('public-');
        
        // Non-user events can't be dragged generally? Actually, logic in original allowed some?
        // Let's stick to the original guard:
        if (!isUserEvent) {
             // Exception: move check-in/out across days? 
             // Original code allowed moving check-in/out across days if it started with acc-
             const activeEvent = dailyTimeline[sourceDayIdx].events.find(e => e.id === activeId);
             if (activeEvent?.id.startsWith('acc-') && activeEvent.sourceId) {
                if (sourceDayIdx !== destDayIdx) {
                    const destDayDate = dailyTimeline[destDayIdx].date;
                    const updates = activeEvent.autoGeneratedType === 'check-in'
                        ? { startDate: destDayDate }
                        : { endDate: destDayDate };
                    updateAccommodation(activeEvent.sourceId, updates);
                }
                return;
             }
             return;
        }

        if (sourceDayIdx === destDayIdx) {
            // Reorder within the same day
            const day = dailyTimeline[sourceDayIdx];
            const allDayEvents = day.events;

            const oldIdxInAll = allDayEvents.findIndex(e => e.id === activeId);
            let newIdxInAll = allDayEvents.findIndex(e => e.id === overId);

            if (newIdxInAll === -1 && overId.startsWith('day-')) {
                newIdxInAll = allDayEvents.length;
            }

            if (oldIdxInAll !== -1 && newIdxInAll !== -1) {
                const reorderedAllEvents = arrayMove([...allDayEvents], oldIdxInAll, newIdxInAll);
                const activeEvent = allDayEvents[oldIdxInAll];

                // Handle User Event Reorder (update time based on surroundings)
                const reorderedUserEvents = reorderedAllEvents.filter(e => !e.isAutoGenerated);
                
                const targetIdx = newIdxInAll;
                const prev = reorderedAllEvents[targetIdx - 1];
                const next = reorderedAllEvents[targetIdx + 1];

                let newTime = activeEvent.startTime;
                
                if (prev && prev.startTime) {
                    const prevEnd = prev.endTime || prev.startTime;
                    const prevMin = timeToMinutes(prevEnd);
                    newTime = minutesToTime(prevMin + 30); 
                } else if (next && next.startTime) {
                    const nextMin = timeToMinutes(next.startTime);
                    newTime = minutesToTime(nextMin - (activeEvent.durationMinutes || 30));
                }
                
                if (newTime && newTime !== activeEvent.startTime) {
                    const userEvIdx = reorderedUserEvents.findIndex(e => e.id === activeId);
                    if (userEvIdx !== -1) {
                        reorderedUserEvents[userEvIdx] = { ...reorderedUserEvents[userEvIdx], startTime: newTime };
                    }
                }

                reorderEvents(sourceDayIdx, reorderedUserEvents);
            }
        } else {
            // Move between days
            const activeEvent = dailyTimeline[sourceDayIdx].events.find(e => e.id === activeId);
            if (!activeEvent) return;

            const destDay = dailyTimeline[destDayIdx];
            const overIdxInAll = destDay.events.findIndex(e => e.id === overId);

            let newPosition: number | undefined = undefined;
            if (overIdxInAll !== -1) {
                newPosition = destDay.events.slice(0, overIdxInAll).filter((e: TripEvent) => !e.isAutoGenerated).length;
            }
            
            let updatedStartTime = activeEvent.startTime;
            if (overIdxInAll !== -1) {
                const prev = destDay.events[overIdxInAll - 1];
                const next = destDay.events[overIdxInAll];
                
                if (prev && prev.startTime) {
                    const prevEnd = prev.endTime || prev.startTime;
                    updatedStartTime = minutesToTime(timeToMinutes(prevEnd) + 30);
                } else if (next && next.startTime) {
                    updatedStartTime = minutesToTime(timeToMinutes(next.startTime) - 30);
                }
            }

            moveEvent(sourceDayIdx, destDayIdx, activeId, newPosition);
            if (updatedStartTime !== activeEvent.startTime) {
                setTimeout(() => {
                    updateEvent(destDayIdx, activeId, { startTime: updatedStartTime });
                }, 0);
            }
        }
    };

    return { handleDragStart, handleDragEnd };
}
