import { useMemo } from 'react';
import { format, parseISO } from 'date-fns';
import { ko } from 'date-fns/locale';
import { Trip, TripEvent, DailyPlan } from '@pplaner/shared';
import { timeToMinutes } from '@pplaner/shared';

export interface EnhancedTimelineDay extends DailyPlan {
    dayOfWeek: string;
    visitSummary: string;
    flexibleEvents: TripEvent[];
    scheduledEvents: TripEvent[];
}

export function useTimelineProcessor(trip: Trip | null, showOnlyBooked: boolean) {
    const timelineWithReservations = useMemo(() => {
        if (!trip) return [];

        const { dailyTimeline, flights, accommodation, publicTransport } = trip;

        return dailyTimeline.map((day) => {
            const dayDate = parseISO(day.date);
            const dayOfWeek = format(dayDate, 'EEEE', { locale: ko });

            // 1. Collect all events for this day
            let dayEvents: TripEvent[] = [...(day.events || [])];

            // Add Flights
            flights?.forEach(flight => {
                if (flight.date === day.date) {
                    dayEvents.push({
                        id: `flight-dep-${flight.id}`,
                        title: `${flight.departureLocation || '출발'} → ${flight.arrivalLocation || '도착'}${flight.flightNumber ? ` (${flight.flightNumber})` : ''}`,
                        startTime: flight.departureTime || '',
                        endTime: flight.departureTime || '',
                        type: 'transport',
                        isFixedTime: true,
                        autoGeneratedType: 'flight',
                        sourceId: flight.id,
                        location: flight.departureLat && flight.departureLng ? {
                            name: flight.departureLocation || '',
                            lat: flight.departureLat,
                            lng: flight.departureLng
                        } : undefined,
                        isAutoGenerated: true,
                        isBooked: flight.isBooked,
                        cost: flight.cost,
                        currency: flight.currency,
                    });
                }
            });

            // Add Accommodations
            accommodation?.forEach(acc => {
                const accIsBooked = acc.status === 'booked';

                if (acc.startDate === day.date) {
                    dayEvents.push({
                        id: `acc-checkin-${acc.id}`,
                        title: `${acc.name} 체크인`,
                        startTime: acc.checkInStartTime || '15:00',
                        endTime: acc.checkInStartTime || '15:00',
                        type: 'accommodation',
                        isFixedTime: true,
                        autoGeneratedType: 'check-in',
                        sourceId: acc.id,
                        location: acc.lat && acc.lng ? {
                            name: acc.location || acc.name,
                            lat: acc.lat,
                            lng: acc.lng
                        } : undefined,
                        isAutoGenerated: true,
                        isBooked: accIsBooked,
                        checkInTime: acc.checkInStartTime,
                        checkOutTime: acc.checkOutEndTime,
                        cost: acc.price,
                        currency: acc.currency,
                    });
                } else if (acc.endDate === day.date) {
                    dayEvents.push({
                        id: `acc-checkout-${acc.id}`,
                        title: `${acc.name} 체크아웃`,
                        startTime: acc.checkOutEndTime || '11:00',
                        endTime: acc.checkOutEndTime || '11:00',
                        type: 'accommodation',
                        isFixedTime: true,
                        autoGeneratedType: 'check-out',
                        sourceId: acc.id,
                        location: acc.lat && acc.lng ? {
                            name: acc.location || acc.name,
                            lat: acc.lat,
                            lng: acc.lng
                        } : undefined,
                        isAutoGenerated: true,
                        isBooked: accIsBooked,
                        checkInTime: acc.checkInStartTime,
                        checkOutTime: acc.checkOutEndTime,
                        cost: acc.price,
                        currency: acc.currency,
                    });
                } else if (dayDate > parseISO(acc.startDate) && dayDate < parseISO(acc.endDate)) {
                    dayEvents.push({
                        id: `acc-stay-${acc.id}-${day.date}`,
                        title: `숙박 중: ${acc.name}`,
                        startTime: '00:00',
                        endTime: '23:59',
                        type: 'accommodation',
                        isFixedTime: false,
                        autoGeneratedType: 'stay',
                        sourceId: acc.id,
                        location: acc.lat && acc.lng ? {
                            name: acc.location || acc.name,
                            lat: acc.lat,
                            lng: acc.lng
                        } : undefined,
                        isAutoGenerated: true,
                        isBooked: accIsBooked,
                        checkInTime: acc.checkInStartTime,
                        checkOutTime: acc.checkOutEndTime,
                        cost: acc.price,
                        currency: acc.currency,
                    });
                }
            });

            // Add Public Transports
            publicTransport?.forEach(pt => {
                if (pt.date === day.date) {
                    dayEvents.push({
                        id: `pt-${pt.id}`,
                        title: `${pt.type === 'train' ? '열차' : pt.type === 'bus' ? '버스' : '대중교통'}${pt.departureLocation ? `: ${pt.departureLocation}` : ''}${pt.arrivalLocation ? ` → ${pt.arrivalLocation}` : ''}`,
                        startTime: pt.departureTime || '',
                        endTime: pt.arrivalTime || '',
                        type: 'transport',
                        isFixedTime: true,
                        autoGeneratedType: 'public-transport',
                        sourceId: pt.id,
                        isAutoGenerated: true,
                        isBooked: pt.isBooked,
                        cost: pt.cost,
                        currency: pt.currency,
                    });
                }
            });

            // 2. Filter if "Show Only Booked" is on
            if (showOnlyBooked) {
                dayEvents = dayEvents.filter(e => e.isBooked || !e.isAutoGenerated);
            }

            // 3. Split Flexible and Scheduled
            const flexibleEvents = dayEvents.filter(e => e.isFlexible && !e.isFixedTime);
            const scheduledEvents = dayEvents.filter(e => !e.isFlexible || e.isFixedTime);

            // 4. Sort Scheduled Events by Start Time
            scheduledEvents.sort((a, b) => {
                const timeA = timeToMinutes(a.startTime);
                const timeB = timeToMinutes(b.startTime);
                if (timeA !== timeB) return timeA - timeB;

                const typePriority: Record<string, number> = {
                    'check-out': 0,
                    'flight': 1,
                    'public-transport': 2,
                    'transport': 3,
                    'activity': 4,
                    'etc': 5,
                    'check-in': 6,
                    'stay': 7
                };
                const priorityA = typePriority[a.autoGeneratedType!] ?? 4;
                const priorityB = typePriority[b.autoGeneratedType!] ?? 4;
                return priorityA - priorityB;
            });

            // 5. Generate Summary
            const dayStays = scheduledEvents.filter(e => e.autoGeneratedType === 'stay');
            const otherEvents = scheduledEvents.filter(e => e.autoGeneratedType !== 'stay');

            const visitNames = otherEvents
                .filter(e => e.location?.name && !e.isAutoGenerated)
                .map(e => e.location!.name.split(',')[0].split(' ')[0])
                .filter((v, i, a) => a.indexOf(v) === i)
                .slice(0, 2);

            const visitSummary = visitNames.length > 0
                ? `${visitNames.join(', ')} 방문`
                : (dayStays.length > 0 ? (dayStays[0].location?.name ? `${dayStays[0].location.name.split(' ')[0]} 숙박` : '숙소 휴식') : '일정 없음');

            return {
                ...day,
                events: [...scheduledEvents, ...flexibleEvents],
                dayOfWeek,
                visitSummary,
                flexibleEvents,
                scheduledEvents
            } as EnhancedTimelineDay;
        });
    }, [trip, showOnlyBooked]);

    return {
        timelineWithReservations
    };
}
