import { collection, doc, getDocs, query, where, orderBy, writeBatch, setDoc, getDoc, deleteDoc, limit, onSnapshot } from 'firebase/firestore';
import { db, auth } from './firebase';
import { Trip, TripEvent } from '../types/trip';
import { TripFootprint, Travelog, TravelogEvent, TravelogDailyPlan } from '../types/record';
import { removeUndefined } from './utils';
import { generateId } from '../types/common';

const TRIPS_COLLECTION = 'trips';
// const FOOTPRINTS_SUB = 'footprints'; // DELETED: Privacy protection requires this to be strictly local to the device
const TRAVELOGS_COLLECTION = 'travelogs';

/**
 * 여행 계획(Trip)을 여행 기록(Travelog)으로 변환합니다.
 * 숙소 체크인/아웃, 항공 대기 시간 등 계획용 물류 정보를 제거하고 핵심 일정만 추출합니다.
 */
export const convertTripToTravelog = (trip: Trip, userId: string): Travelog => {
    const now = new Date().toISOString();
    
    // 타임라인 변환
    const timeline: TravelogDailyPlan[] = (trip.dailyTimeline || []).map(day => ({
        day: day.day,
        date: day.date,
        events: (day.events || [])
            .filter(event => {
                // 물류 전용 자동 생성 이벤트(체크인/아웃 등)는 제외하거나 간소화
                if (event.isAutoGenerated && (event.autoGeneratedType === 'check-in' || event.autoGeneratedType === 'check-out')) {
                    return false;
                }
                return true;
            })
            .map(event => ({
                id: event.id,
                title: event.title,
                type: 'activity', // 여행 계획에서 가져온 것은 기본적으로 활동으로 처리
                startTime: event.startTime,
                endTime: event.endTime,
                location: event.location,
                memo: event.memo,
                imageUrls: event.imageUrls,
                mainCategory: event.mainCategory,
                subCategory: event.subCategory,
                isPointInTime: event.isPointInTime
            }))
    }));

    return {
        id: trip.id,
        tripId: trip.id,
        userId: userId,
        title: trip.title,
        summary: trip.memo || '',
        theme: trip.theme || '힐링',
        memberCounts: trip.memberCounts || { me: 1, partner: 0, family: 0, friends: 0 },
        status: 'draft',
        isPublic: false,
        sourceContext: 'plan_only',
        timeline: timeline,
        sections: [
            {
                id: generateId(),
                type: 'text',
                content: '',
                contentJson: {
                    type: 'doc',
                    content: [
                        { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '여행의 시작' }] },
                        { type: 'paragraph', content: [{ type: 'text', text: '소중한 여행의 기억을 남겨보세요.' }] }
                    ]
                }
            }
        ],
        createdAt: now,
        updatedAt: now
    };
};

/**
 * ─── 발자취 (TripFootprint) 서비스 ─────────────────────────────────
 * @privacy 분리됨: 원시 발자취 데이터는 민감한 개인 정보이므로 Firestore와 서버로 절대 동기화되지 않습니다.
 * 모바일 앱(React Native / Expo) 측의 로컬 암호화 스토리지(SecureStore/MMKV)에 직접 접근하는 로직으로 대체되어야 합니다.
 * 공유 패키지에서는 이 영역의 CRUD 로직을 의도적으로 방치/삭제합니다.
 */

// export const saveFootprintsBatch = ... (Deleted for Privacy)
// export const getTripFootprints = ... (Deleted for Privacy)

/**
 * ─── 여행기 (Travelog) 서비스 ────────────────────────────────────
 * 사용자가 발자취를 바탕으로 일부 거점만 포함시켜 직접 발행하기를 선택한 경우에 한해, 
 * 서버와 동기화되고 웹으로 노출됩니다.
 */
/**
 * 새로운 여행기 저장 또는 업데이트
 */
export const saveTravelog = async (travelog: Travelog) => {
    if (!auth.currentUser || auth.currentUser.uid !== travelog.userId) {
        throw new Error("Authentication mismatch for travelog");
    }
    try {
        const ref = doc(db, TRAVELOGS_COLLECTION, travelog.id);
        const dataToSave = {
            ...travelog,
            updatedAt: new Date().toISOString() // 항상 최신 수정 일자 반영
        };
        await setDoc(ref, removeUndefined(dataToSave), { merge: true });
    } catch (error) {
        console.error("[RecordService] Error saving travelog:", error);
        throw error;
    }
};

/**
 *特定の 사용자의 모든 여행기 조회
 */
export const getUserTravelogs = async (userId: string, isPublicOnly: boolean = false): Promise<Travelog[]> => {
    try {
        let q = query(
            collection(db, TRAVELOGS_COLLECTION),
            where("userId", "==", userId),
            orderBy("createdAt", "desc")
        );

        if (isPublicOnly) {
            q = query(q, where("status", "==", "published"));
        }

        const snap = await getDocs(q);
        return snap.docs.map(doc => doc.data() as Travelog);
    } catch (error) {
        console.error("[RecordService] Error getting user travelogs:", error);
        return [];
    }
};

/**
 * 특정 여행기 상세 조회
 */
export const getTravelog = async (travelogId: string): Promise<Travelog | null> => {
    try {
        const docRef = doc(db, TRAVELOGS_COLLECTION, travelogId);
        const docSnap = await getDoc(docRef);
        return docSnap.exists() ? (docSnap.data() as Travelog) : null;
    } catch (error) {
        console.error("[RecordService] Error getting travelog:", error);
        throw error;
    }
};

/**
 * 여행기 삭제
 */
export const deleteTravelog = async (travelogId: string, authorId: string) => {
    if (!auth.currentUser || auth.currentUser.uid !== authorId) {
        throw new Error("Authentication mismatch for deletion");
    }
    try {
        await deleteDoc(doc(db, TRAVELOGS_COLLECTION, travelogId));
    } catch (error) {
        console.error("[RecordService] Error deleting travelog:", error);
        throw error;
    }
};

/**
 * 사용자의 여행기 목록을 실시간으로 구독합니다.
 */
export const subscribeToUserTravelogs = (userId: string, onUpdate: (travelogs: Travelog[]) => void) => {
    const q = query(
        collection(db, TRAVELOGS_COLLECTION),
        where("userId", "==", userId),
        orderBy("createdAt", "desc")
    );

    return onSnapshot(q, (snapshot) => {
        const travelogs = snapshot.docs.map(doc => doc.data() as Travelog);
        onUpdate(travelogs);
    }, (error) => {
        console.error("[RecordService] Error subscribing to travelogs:", error);
    });
};

/**
 * 트래블로그 타임라인을 분석하여 가장 빈도가 높은 대표 지역을 추출합니다.
 */
import { getRegionNamesByIds } from './region-service';
import { RegionIds } from '../types/common';

export const calculateTravelogRepresentativeRegion = async (travelog: Travelog) => {
    const counts: Record<string, { count: number, ids: RegionIds }> = {};
    
    if (!travelog.timeline) return null;

    for (const day of travelog.timeline) {
        if (!day.events) continue;
        for (const event of day.events) {
            // location 정보가 있고 국가 ID가 최소한이라도 있어야 함
            if (event.location?.countryId) {
                const cityPart = event.location.cityId || 'none';
                const prefPart = event.location.prefectureId || 'none';
                const key = `${event.location.countryId}_${prefPart}_${cityPart}`;
                
                if (!counts[key]) {
                    counts[key] = { 
                        count: 0, 
                        ids: { 
                            countryId: event.location.countryId,
                            prefectureId: event.location.prefectureId,
                            cityId: event.location.cityId
                        }
                    };
                }
                counts[key].count++;
            }
        }
    }
    
    // 가장 높은 빈도 찾기
    let winnerIds: RegionIds | null = null;
    let max = 0;
    
    for (const key in counts) {
        if (counts[key].count > max) {
            max = counts[key].count;
            winnerIds = counts[key].ids;
        }
    }
    
    if (!winnerIds) return null;
    
    // 지역 명칭 확보
    const names = await getRegionNamesByIds(winnerIds);
    return {
        ...winnerIds,
        ...names,
        frequency: max
    };
};
